/*!
 * jQuery JavaScript Library v1.9.0
 * http://jquery.com/
 *
 * Includes Sizzle.js
 * http://sizzlejs.com/
 *
 * Copyright 2005, 2012 jQuery Foundation, Inc. and other contributors
 * Released under the MIT license
 * http://jquery.org/license
 *
 * Date: 2013-1-14
 * Changed by Sergey Davydov <webmaster@collection.com.ua>: Remove r20 - %20 replace in rows 7265, 7334  */
(function(C,t){function Wa(a){var b=a.length,d=c.type(a);if(c.isWindow(a))return false;if(a.nodeType===1&&b)return true;return d==="array"||d!=="function"&&(b===0||typeof b==="number"&&b>0&&b-1 in a)}function wc(a){var b=vb[a]={};c.each(a.match(ja)||[],function(d,e){b[e]=true});return b}function wb(a,b,d,e){if(c.acceptData(a)){var f=c.expando,g=typeof b==="string",h=a.nodeType,j=h?c.cache:a,m=h?a[f]:a[f]&&f;if(!((!m||!j[m]||!e&&!j[m].data)&&g&&d===t)){if(!m)if(h)a[f]=m=xa.pop()||c.guid++;else m=f;
if(!j[m]){j[m]={};if(!h)j[m].toJSON=c.noop}if(typeof b==="object"||typeof b==="function")if(e)j[m]=c.extend(j[m],b);else j[m].data=c.extend(j[m].data,b);a=j[m];if(!e){if(!a.data)a.data={};a=a.data}if(d!==t)a[c.camelCase(b)]=d;if(g){d=a[b];if(d==null)d=a[c.camelCase(b)]}else d=a;return d}}}function xb(a,b,d){if(c.acceptData(a)){var e,f,g,h=a.nodeType,j=h?c.cache:a,m=h?a[c.expando]:c.expando;if(j[m]){if(b)if(e=d?j[m]:j[m].data){if(c.isArray(b))b=b.concat(c.map(b,c.camelCase));else if(b in e)b=[b];else{b=
c.camelCase(b);b=b in e?[b]:b.split(" ")}f=0;for(g=b.length;f<g;f++)delete e[b[f]];if(!(d?Xa:c.isEmptyObject)(e))return}if(!d){delete j[m].data;if(!Xa(j[m]))return}if(h)c.cleanData([a],true);else if(c.support.deleteExpando||j!=j.window)delete j[m];else j[m]=null}}}function yb(a,b,d){if(d===t&&a.nodeType===1){d="data-"+b.replace(xc,"-$1").toLowerCase();d=a.getAttribute(d);if(typeof d==="string"){try{d=d==="true"?true:d==="false"?false:d==="null"?null:+d+""===d?+d:yc.test(d)?c.parseJSON(d):d}catch(e){}c.data(a,
b,d)}else d=t}return d}function Xa(a){for(var b in a)if(!(b==="data"&&c.isEmptyObject(a[b])))if(b!=="toJSON")return false;return true}function Ka(){return true}function ya(){return false}function zb(a,b){do a=a[b];while(a&&a.nodeType!==1);return a}function Ab(a,b,d){b=b||0;if(c.isFunction(b))return c.grep(a,function(f,g){return!!b.call(f,g,f)===d});else if(b.nodeType)return c.grep(a,function(f){return f===b===d});else if(typeof b==="string"){var e=c.grep(a,function(f){return f.nodeType===1});if(zc.test(b))return c.filter(b,
e,!d);else b=c.filter(b,e)}return c.grep(a,function(f){return c.inArray(f,b)>=0===d})}function Bb(a){var b=Cb.split("|");a=a.createDocumentFragment();if(a.createElement)for(;b.length;)a.createElement(b.pop());return a}function Db(a){var b=a.getAttributeNode("type");a.type=(b&&b.specified)+"/"+a.type;return a}function Eb(a){var b=Ac.exec(a.type);if(b)a.type=b[1];else a.removeAttribute("type");return a}function Ya(a,b){for(var d,e=0;(d=a[e])!=null;e++)c._data(d,"globalEval",!b||c._data(b[e],"globalEval"))}
function Fb(a,b){if(!(b.nodeType!==1||!c.hasData(a))){var d,e,f;e=c._data(a);var g=c._data(b,e),h=e.events;if(h){delete g.handle;g.events={};for(d in h){e=0;for(f=h[d].length;e<f;e++)c.event.add(b,d,h[d][e])}}if(g.data)g.data=c.extend({},g.data)}}function aa(a,b){var d,e,f=0,g=typeof a.getElementsByTagName!=="undefined"?a.getElementsByTagName(b||"*"):typeof a.querySelectorAll!=="undefined"?a.querySelectorAll(b||"*"):t;if(!g){g=[];for(d=a.childNodes||a;(e=d[f])!=null;f++)!b||c.nodeName(e,b)?g.push(e):
c.merge(g,aa(e,b))}return b===t||b&&c.nodeName(a,b)?c.merge([a],g):g}function Bc(a){if(Za.test(a.type))a.defaultChecked=a.checked}function Gb(a,b){if(b in a)return b;for(var d=b.charAt(0).toUpperCase()+b.slice(1),e=b,f=Hb.length;f--;){b=Hb[f]+d;if(b in a)return b}return e}function Ha(a,b){a=b||a;return c.css(a,"display")==="none"||!c.contains(a.ownerDocument,a)}function Ib(a,b){for(var d,e=[],f=0,g=a.length;f<g;f++){d=a[f];if(d.style){e[f]=c._data(d,"olddisplay");if(b){if(!e[f]&&d.style.display===
"none")d.style.display="";if(d.style.display===""&&Ha(d))e[f]=c._data(d,"olddisplay",Jb(d.nodeName))}else!e[f]&&!Ha(d)&&c._data(d,"olddisplay",c.css(d,"display"))}}for(f=0;f<g;f++){d=a[f];if(d.style)if(!b||d.style.display==="none"||d.style.display==="")d.style.display=b?e[f]||"":"none"}return a}function Kb(a,b,d){return(a=Cc.exec(b))?Math.max(0,a[1]-(d||0))+(a[2]||"px"):b}function Lb(a,b,d,e,f){b=d===(e?"border":"content")?4:b==="width"?1:0;for(var g=0;b<4;b+=2){if(d==="margin")g+=c.css(a,d+pa[b],
true,f);if(e){if(d==="content")g-=c.css(a,"padding"+pa[b],true,f);if(d!=="margin")g-=c.css(a,"border"+pa[b]+"Width",true,f)}else{g+=c.css(a,"padding"+pa[b],true,f);if(d!=="padding")g+=c.css(a,"border"+pa[b]+"Width",true,f)}}return g}function Mb(a,b,d){var e=true,f=b==="width"?a.offsetWidth:a.offsetHeight,g=qa(a),h=c.support.boxSizing&&c.css(a,"boxSizing",false,g)==="border-box";if(f<=0||f==null){f=ra(a,b,g);if(f<0||f==null)f=a.style[b];if(La.test(f))return f;e=h&&(c.support.boxSizingReliable||f===
a.style[b]);f=parseFloat(f)||0}return f+Lb(a,b,d||(h?"border":"content"),e,g)+"px"}function Jb(a){var b=A,d=Nb[a];if(!d){d=Ob(a,b);if(d==="none"||!d){Ia=(Ia||c("<iframe frameborder='0' width='0' height='0'/>").css("cssText","display:block !important")).appendTo(b.documentElement);b=(Ia[0].contentWindow||Ia[0].contentDocument).document;b.write("<!doctype html><html><body>");b.close();d=Ob(a,b);Ia.detach()}Nb[a]=d}return d}function Ob(a,b){var d=c(b.createElement(a)).appendTo(b.body),e=c.css(d[0],"display");
d.remove();return e}function $a(a,b,d,e){var f;if(c.isArray(b))c.each(b,function(g,h){d||Dc.test(a)?e(a,h):$a(a+"["+(typeof h==="object"?g:"")+"]",h,d,e)});else if(!d&&c.type(b)==="object")for(f in b)$a(a+"["+f+"]",b[f],d,e);else e(a,b)}function Pb(a){return function(b,d){if(typeof b!=="string"){d=b;b="*"}var e,f=0,g=b.toLowerCase().match(ja)||[];if(c.isFunction(d))for(;e=g[f++];)if(e[0]==="+"){e=e.slice(1)||"*";(a[e]=a[e]||[]).unshift(d)}else(a[e]=a[e]||[]).push(d)}}function Qb(a,b,d,e){function f(j){var m;
g[j]=true;c.each(a[j]||[],function(p,r){var n=r(b,d,e);if(typeof n==="string"&&!h&&!g[n]){b.dataTypes.unshift(n);f(n);return false}else if(h)return!(m=n)});return m}var g={},h=a===ab;return f(b.dataTypes[0])||!g["*"]&&f("*")}function bb(a,b){var d,e,f=c.ajaxSettings.flatOptions||{};for(d in b)if(b[d]!==t)(f[d]?a:e||(e={}))[d]=b[d];e&&c.extend(true,a,e);return a}function Rb(){try{return new C.XMLHttpRequest}catch(a){}}function Sb(){setTimeout(function(){za=t});return za=c.now()}function Ec(a,b){c.each(b,
function(d,e){for(var f=(Ja[d]||[]).concat(Ja["*"]),g=0,h=f.length;g<h;g++)if(f[g].call(a,d,e))break})}function Tb(a,b,d){var e,f=0,g=Ma.length,h=c.Deferred().always(function(){delete j.elem}),j=function(){if(e)return false;var p=za||Sb();p=Math.max(0,m.startTime+m.duration-p);for(var r=1-(p/m.duration||0),n=0,v=m.tweens.length;n<v;n++)m.tweens[n].run(r);h.notifyWith(a,[m,r,p]);if(r<1&&v)return p;else{h.resolveWith(a,[m]);return false}},m=h.promise({elem:a,props:c.extend({},b),opts:c.extend(true,
{specialEasing:{}},d),originalProperties:b,originalOptions:d,startTime:za||Sb(),duration:d.duration,tweens:[],createTween:function(p,r){var n=c.Tween(a,m.opts,p,r,m.opts.specialEasing[p]||m.opts.easing);m.tweens.push(n);return n},stop:function(p){var r=0,n=p?m.tweens.length:0;if(e)return this;for(e=true;r<n;r++)m.tweens[r].run(1);p?h.resolveWith(a,[m,p]):h.rejectWith(a,[m,p]);return this}});d=m.props;for(Fc(d,m.opts.specialEasing);f<g;f++)if(b=Ma[f].call(m,a,d,m.opts))return b;Ec(m,d);c.isFunction(m.opts.start)&&
m.opts.start.call(a,m);c.fx.timer(c.extend(j,{elem:a,anim:m,queue:m.opts.queue}));return m.progress(m.opts.progress).done(m.opts.done,m.opts.complete).fail(m.opts.fail).always(m.opts.always)}function Fc(a,b){var d,e,f,g,h;for(d in a){e=c.camelCase(d);f=b[e];g=a[d];if(c.isArray(g)){f=g[1];g=a[d]=g[0]}if(d!==e){a[e]=g;delete a[d]}if((h=c.cssHooks[e])&&"expand"in h){g=h.expand(g);delete a[e];for(d in g)if(!(d in a)){a[d]=g[d];b[d]=f}}else b[e]=f}}function ba(a,b,d,e,f){return new ba.prototype.init(a,
b,d,e,f)}function Na(a,b){var d,e={height:a},f=0;for(b=b?1:0;f<4;f+=2-b){d=pa[f];e["margin"+d]=e["padding"+d]=a}if(b)e.opacity=e.width=a;return e}function Ub(a){return c.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var Vb,Oa,A=C.document,Aa=C.location,Gc=C.jQuery,Hc=C.$,Pa={},xa=[],Wb=xa.concat,cb=xa.push,sa=xa.slice,Xb=xa.indexOf,Ic=Pa.toString,db=Pa.hasOwnProperty,eb="1.9.0".trim,c=function(a,b){return new c.fn.init(a,b,Vb)},Qa=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,ja=
/\S+/g,Jc=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,Kc=/^(?:(<[\w\W]+>)[^>]*|#([\w-]*))$/,Yb=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,Lc=/^[\],:{}\s]*$/,Mc=/(?:^|:|,)(?:\s*\[)+/g,Nc=/\\(?:["\\\/bfnrt]|u[\da-fA-F]{4})/g,Oc=/"[^"\\\r\n]*"|true|false|null|-?(?:\d+\.|)\d+(?:[eE][+-]?\d+|)/g,Pc=/^-ms-/,Qc=/-([\da-z])/gi,Rc=function(a,b){return b.toUpperCase()},Ra=function(){if(A.addEventListener){A.removeEventListener("DOMContentLoaded",Ra,false);c.ready()}else if(A.readyState==="complete"){A.detachEvent("onreadystatechange",
Ra);c.ready()}};c.fn=c.prototype={jquery:"1.9.0",constructor:c,init:function(a,b,d){var e;if(!a)return this;if(typeof a==="string")if((e=a.charAt(0)==="<"&&a.charAt(a.length-1)===">"&&a.length>=3?[null,a,null]:Kc.exec(a))&&(e[1]||!b)){if(e[1]){b=b instanceof c?b[0]:b;c.merge(this,c.parseHTML(e[1],b&&b.nodeType?b.ownerDocument||b:A,true));if(Yb.test(e[1])&&c.isPlainObject(b))for(e in b)c.isFunction(this[e])?this[e](b[e]):this.attr(e,b[e])}else{if((b=A.getElementById(e[2]))&&b.parentNode){if(b.id!==
e[2])return d.find(a);this.length=1;this[0]=b}this.context=A;this.selector=a}return this}else return!b||b.jquery?(b||d).find(a):this.constructor(b).find(a);else if(a.nodeType){this.context=this[0]=a;this.length=1;return this}else if(c.isFunction(a))return d.ready(a);if(a.selector!==t){this.selector=a.selector;this.context=a.context}return c.makeArray(a,this)},selector:"",length:0,size:function(){return this.length},toArray:function(){return sa.call(this)},get:function(a){return a==null?this.toArray():
a<0?this[this.length+a]:this[a]},pushStack:function(a){a=c.merge(this.constructor(),a);a.prevObject=this;a.context=this.context;return a},each:function(a,b){return c.each(this,a,b)},ready:function(a){c.ready.promise().done(a);return this},slice:function(){return this.pushStack(sa.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},eq:function(a){var b=this.length;a=+a+(a<0?b:0);return this.pushStack(a>=0&&a<b?[this[a]]:[])},map:function(a){return this.pushStack(c.map(this,
function(b,d){return a.call(b,d,b)}))},end:function(){return this.prevObject||this.constructor(null)},push:cb,sort:[].sort,splice:[].splice};c.fn.init.prototype=c.fn;c.extend=c.fn.extend=function(){var a,b,d,e,f,g=arguments[0]||{},h=1,j=arguments.length,m=false;if(typeof g==="boolean"){m=g;g=arguments[1]||{};h=2}if(typeof g!=="object"&&!c.isFunction(g))g={};if(j===h){g=this;--h}for(;h<j;h++)if((a=arguments[h])!=null)for(b in a){d=g[b];e=a[b];if(g!==e)if(m&&e&&(c.isPlainObject(e)||(f=c.isArray(e)))){if(f){f=
false;d=d&&c.isArray(d)?d:[]}else d=d&&c.isPlainObject(d)?d:{};g[b]=c.extend(m,d,e)}else if(e!==t)g[b]=e}return g};c.extend({noConflict:function(a){if(C.$===c)C.$=Hc;if(a&&C.jQuery===c)C.jQuery=Gc;return c},isReady:false,readyWait:1,holdReady:function(a){if(a)c.readyWait++;else c.ready(true)},ready:function(a){if(!(a===true?--c.readyWait:c.isReady)){if(!A.body)return setTimeout(c.ready);c.isReady=true;if(!(a!==true&&--c.readyWait>0)){Oa.resolveWith(A,[c]);c.fn.trigger&&c(A).trigger("ready").off("ready")}}},
isFunction:function(a){return c.type(a)==="function"},isArray:Array.isArray||function(a){return c.type(a)==="array"},isWindow:function(a){return a!=null&&a==a.window},isNumeric:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},type:function(a){if(a==null)return String(a);return typeof a==="object"||typeof a==="function"?Pa[Ic.call(a)]||"object":typeof a},isPlainObject:function(a){if(!a||c.type(a)!=="object"||a.nodeType||c.isWindow(a))return false;try{if(a.constructor&&!db.call(a,"constructor")&&
!db.call(a.constructor.prototype,"isPrototypeOf"))return false}catch(b){return false}for(var d in a);return d===t||db.call(a,d)},isEmptyObject:function(a){for(var b in a)return false;return true},error:function(a){throw Error(a);},parseHTML:function(a,b,d){if(!a||typeof a!=="string")return null;if(typeof b==="boolean"){d=b;b=false}b=b||A;var e=Yb.exec(a);d=!d&&[];if(e)return[b.createElement(e[1])];e=c.buildFragment([a],b,d);d&&c(d).remove();return c.merge([],e.childNodes)},parseJSON:function(a){if(C.JSON&&
C.JSON.parse)return C.JSON.parse(a);if(a===null)return a;if(typeof a==="string")if(a=c.trim(a))if(Lc.test(a.replace(Nc,"@").replace(Oc,"]").replace(Mc,"")))return(new Function("return "+a))();c.error("Invalid JSON: "+a)},parseXML:function(a){var b,d;if(!a||typeof a!=="string")return null;try{if(C.DOMParser){d=new DOMParser;b=d.parseFromString(a,"text/xml")}else{b=new ActiveXObject("Microsoft.XMLDOM");b.async="false";b.loadXML(a)}}catch(e){b=t}if(!b||!b.documentElement||b.getElementsByTagName("parsererror").length)c.error("Invalid XML: "+
a);return b},noop:function(){},globalEval:function(a){if(a&&c.trim(a))(C.execScript||function(b){C.eval.call(C,b)})(a)},camelCase:function(a){return a.replace(Pc,"ms-").replace(Qc,Rc)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()},each:function(a,b,d){var e,f=0,g=a.length;e=Wa(a);if(d)if(e)for(;f<g;f++){e=b.apply(a[f],d);if(e===false)break}else for(f in a){e=b.apply(a[f],d);if(e===false)break}else if(e)for(;f<g;f++){e=b.call(a[f],f,a[f]);if(e===false)break}else for(f in a){e=
b.call(a[f],f,a[f]);if(e===false)break}return a},trim:eb&&!eb.call("\ufeff\u00a0")?function(a){return a==null?"":eb.call(a)}:function(a){return a==null?"":(a+"").replace(Jc,"")},makeArray:function(a,b){var d=b||[];if(a!=null)Wa(Object(a))?c.merge(d,typeof a==="string"?[a]:a):cb.call(d,a);return d},inArray:function(a,b,d){var e;if(b){if(Xb)return Xb.call(b,a,d);e=b.length;for(d=d?d<0?Math.max(0,e+d):d:0;d<e;d++)if(d in b&&b[d]===a)return d}return-1},merge:function(a,b){var d=b.length,e=a.length,f=
0;if(typeof d==="number")for(;f<d;f++)a[e++]=b[f];else for(;b[f]!==t;)a[e++]=b[f++];a.length=e;return a},grep:function(a,b,d){var e,f=[],g=0,h=a.length;for(d=!!d;g<h;g++){e=!!b(a[g],g);d!==e&&f.push(a[g])}return f},map:function(a,b,d){var e,f=0,g=a.length,h=[];if(Wa(a))for(;f<g;f++){e=b(a[f],f,d);if(e!=null)h[h.length]=e}else for(f in a){e=b(a[f],f,d);if(e!=null)h[h.length]=e}return Wb.apply([],h)},guid:1,proxy:function(a,b){var d,e;if(typeof b==="string"){d=a[b];b=a;a=d}if(!c.isFunction(a))return t;
e=sa.call(arguments,2);d=function(){return a.apply(b||this,e.concat(sa.call(arguments)))};d.guid=a.guid=a.guid||c.guid++;return d},access:function(a,b,d,e,f,g,h){var j=0,m=a.length,p=d==null;if(c.type(d)==="object"){f=true;for(j in d)c.access(a,b,j,d[j],true,g,h)}else if(e!==t){f=true;c.isFunction(e)||(h=true);if(p)if(h){b.call(a,e);b=null}else{p=b;b=function(r,n,v){return p.call(c(r),v)}}if(b)for(;j<m;j++)b(a[j],d,h?e:e.call(a[j],j,b(a[j],d)))}return f?a:p?b.call(a):m?b(a[0],d):g},now:function(){return(new Date).getTime()}});
c.ready.promise=function(a){if(!Oa){Oa=c.Deferred();if(A.readyState==="complete")setTimeout(c.ready);else if(A.addEventListener){A.addEventListener("DOMContentLoaded",Ra,false);C.addEventListener("load",c.ready,false)}else{A.attachEvent("onreadystatechange",Ra);C.attachEvent("onload",c.ready);var b=false;try{b=C.frameElement==null&&A.documentElement}catch(d){}b&&b.doScroll&&function e(){if(!c.isReady){try{b.doScroll("left")}catch(f){return setTimeout(e,50)}c.ready()}}()}}return Oa.promise(a)};c.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),
function(a,b){Pa["[object "+b+"]"]=b.toLowerCase()});Vb=c(A);var vb={};c.Callbacks=function(a){a=typeof a==="string"?vb[a]||wc(a):c.extend({},a);var b,d,e,f,g,h,j=[],m=!a.once&&[],p=function(n){b=a.memory&&n;d=true;h=f||0;f=0;g=j.length;for(e=true;j&&h<g;h++)if(j[h].apply(n[0],n[1])===false&&a.stopOnFalse){b=false;break}e=false;if(j)if(m)m.length&&p(m.shift());else if(b)j=[];else r.disable()},r={add:function(){if(j){var n=j.length;(function v(y){c.each(y,function(O,X){var V=c.type(X);if(V==="function"){if(!a.unique||
!r.has(X))j.push(X)}else X&&X.length&&V!=="string"&&v(X)})})(arguments);if(e)g=j.length;else if(b){f=n;p(b)}}return this},remove:function(){j&&c.each(arguments,function(n,v){for(var y;(y=c.inArray(v,j,y))>-1;){j.splice(y,1);if(e){y<=g&&g--;y<=h&&h--}}});return this},has:function(n){return c.inArray(n,j)>-1},empty:function(){j=[];return this},disable:function(){j=m=b=t;return this},disabled:function(){return!j},lock:function(){m=t;b||r.disable();return this},locked:function(){return!m},fireWith:function(n,
v){v=v||[];v=[n,v.slice?v.slice():v];if(j&&(!d||m))e?m.push(v):p(v);return this},fire:function(){r.fireWith(this,arguments);return this},fired:function(){return!!d}};return r};c.extend({Deferred:function(a){var b=[["resolve","done",c.Callbacks("once memory"),"resolved"],["reject","fail",c.Callbacks("once memory"),"rejected"],["notify","progress",c.Callbacks("memory")]],d="pending",e={state:function(){return d},always:function(){f.done(arguments).fail(arguments);return this},then:function(){var g=
arguments;return c.Deferred(function(h){c.each(b,function(j,m){var p=m[0],r=c.isFunction(g[j])&&g[j];f[m[1]](function(){var n=r&&r.apply(this,arguments);n&&c.isFunction(n.promise)?n.promise().done(h.resolve).fail(h.reject).progress(h.notify):h[p+"With"](this===e?h.promise():this,r?[n]:arguments)})});g=null}).promise()},promise:function(g){return g!=null?c.extend(g,e):e}},f={};e.pipe=e.then;c.each(b,function(g,h){var j=h[2],m=h[3];e[h[1]]=j.add;m&&j.add(function(){d=m},b[g^1][2].disable,b[2][2].lock);
f[h[0]]=function(){f[h[0]+"With"](this===f?e:this,arguments);return this};f[h[0]+"With"]=j.fireWith});e.promise(f);a&&a.call(f,f);return f},when:function(a){var b=0,d=sa.call(arguments),e=d.length,f=e!==1||a&&c.isFunction(a.promise)?e:0,g=f===1?a:c.Deferred(),h=function(r,n,v){return function(y){n[r]=this;v[r]=arguments.length>1?sa.call(arguments):y;if(v===j)g.notifyWith(n,v);else--f||g.resolveWith(n,v)}},j,m,p;if(e>1){j=Array(e);m=Array(e);for(p=Array(e);b<e;b++)if(d[b]&&c.isFunction(d[b].promise))d[b].promise().done(h(b,
p,d)).fail(g.reject).progress(h(b,m,j));else--f}f||g.resolveWith(p,d);return g.promise()}});c.support=function(){var a,b,d,e,f,g,h,j=A.createElement("div");j.setAttribute("className","t");j.innerHTML="  <link/><table></table><a href='/a'>a</a><input type='checkbox'/>";b=j.getElementsByTagName("*");d=j.getElementsByTagName("a")[0];if(!b||!d||!b.length)return{};e=A.createElement("select");f=e.appendChild(A.createElement("option"));b=j.getElementsByTagName("input")[0];d.style.cssText="top:1px;float:left;opacity:.5";
a={getSetAttribute:j.className!=="t",leadingWhitespace:j.firstChild.nodeType===3,tbody:!j.getElementsByTagName("tbody").length,htmlSerialize:!!j.getElementsByTagName("link").length,style:/top/.test(d.getAttribute("style")),hrefNormalized:d.getAttribute("href")==="/a",opacity:/^0.5/.test(d.style.opacity),cssFloat:!!d.style.cssFloat,checkOn:!!b.value,optSelected:f.selected,enctype:!!A.createElement("form").enctype,html5Clone:A.createElement("nav").cloneNode(true).outerHTML!=="<:nav></:nav>",boxModel:A.compatMode===
"CSS1Compat",deleteExpando:true,noCloneEvent:true,inlineBlockNeedsLayout:false,shrinkWrapBlocks:false,reliableMarginRight:true,boxSizingReliable:true,pixelPosition:false};b.checked=true;a.noCloneChecked=b.cloneNode(true).checked;e.disabled=true;a.optDisabled=!f.disabled;try{delete j.test}catch(m){a.deleteExpando=false}b=A.createElement("input");b.setAttribute("value","");a.input=b.getAttribute("value")==="";b.value="t";b.setAttribute("type","radio");a.radioValue=b.value==="t";b.setAttribute("checked",
"t");b.setAttribute("name","t");d=A.createDocumentFragment();d.appendChild(b);a.appendChecked=b.checked;a.checkClone=d.cloneNode(true).cloneNode(true).lastChild.checked;if(j.attachEvent){j.attachEvent("onclick",function(){a.noCloneEvent=false});j.cloneNode(true).click()}for(h in{submit:true,change:true,focusin:true}){j.setAttribute(d="on"+h,"t");a[h+"Bubbles"]=d in C||j.attributes[d].expando===false}j.style.backgroundClip="content-box";j.cloneNode(true).style.backgroundClip="";a.clearCloneStyle=j.style.backgroundClip===
"content-box";c(function(){var p,r,n=A.getElementsByTagName("body")[0];if(n){p=A.createElement("div");p.style.cssText="border:0;width:0;height:0;position:absolute;top:0;left:-9999px;margin-top:1px";n.appendChild(p).appendChild(j);j.innerHTML="<table><tr><td></td><td>t</td></tr></table>";r=j.getElementsByTagName("td");r[0].style.cssText="padding:0;margin:0;border:0;display:none";g=r[0].offsetHeight===0;r[0].style.display="";r[1].style.display="none";a.reliableHiddenOffsets=g&&r[0].offsetHeight===0;
j.innerHTML="";j.style.cssText="box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;padding:1px;border:1px;display:block;width:4px;margin-top:1%;position:absolute;top:1%;";a.boxSizing=j.offsetWidth===4;a.doesNotIncludeMarginInBodyOffset=n.offsetTop!==1;if(C.getComputedStyle){a.pixelPosition=(C.getComputedStyle(j,null)||{}).top!=="1%";a.boxSizingReliable=(C.getComputedStyle(j,null)||{width:"4px"}).width==="4px";r=j.appendChild(A.createElement("div"));r.style.cssText=j.style.cssText=
"padding:0;margin:0;border:0;display:block;box-sizing:content-box;-moz-box-sizing:content-box;-webkit-box-sizing:content-box;";r.style.marginRight=r.style.width="0";j.style.width="1px";a.reliableMarginRight=!parseFloat((C.getComputedStyle(r,null)||{}).marginRight)}if(typeof j.style.zoom!=="undefined"){j.innerHTML="";j.style.cssText="padding:0;margin:0;border:0;display:block;box-sizing:content-box;-moz-box-sizing:content-box;-webkit-box-sizing:content-box;width:1px;padding:1px;display:inline;zoom:1";
a.inlineBlockNeedsLayout=j.offsetWidth===3;j.style.display="block";j.innerHTML="<div></div>";j.firstChild.style.width="5px";a.shrinkWrapBlocks=j.offsetWidth!==3;n.style.zoom=1}n.removeChild(p);j=null}});b=e=d=f=d=b=null;return a}();var yc=/(?:\{[\s\S]*\}|\[[\s\S]*\])$/,xc=/([A-Z])/g;c.extend({cache:{},expando:"jQuery"+("1.9.0"+Math.random()).replace(/\D/g,""),noData:{embed:true,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:true},hasData:function(a){a=a.nodeType?c.cache[a[c.expando]]:
a[c.expando];return!!a&&!Xa(a)},data:function(a,b,d){return wb(a,b,d,false)},removeData:function(a,b){return xb(a,b,false)},_data:function(a,b,d){return wb(a,b,d,true)},_removeData:function(a,b){return xb(a,b,true)},acceptData:function(a){var b=a.nodeName&&c.noData[a.nodeName.toLowerCase()];return!b||b!==true&&a.getAttribute("classid")===b}});c.fn.extend({data:function(a,b){var d,e,f=this[0],g=0,h=null;if(a===t){if(this.length){h=c.data(f);if(f.nodeType===1&&!c._data(f,"parsedAttrs")){for(d=f.attributes;g<
d.length;g++){e=d[g].name;if(!e.indexOf("data-")){e=c.camelCase(e.substring(5));yb(f,e,h[e])}}c._data(f,"parsedAttrs",true)}}return h}if(typeof a==="object")return this.each(function(){c.data(this,a)});return c.access(this,function(j){if(j===t)return f?yb(f,a,c.data(f,a)):null;this.each(function(){c.data(this,a,j)})},null,b,arguments.length>1,null,true)},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){var e;if(a){b=(b||"fx")+"queue";e=c._data(a,
b);if(d)if(!e||c.isArray(d))e=c._data(a,b,c.makeArray(d));else e.push(d);return e||[]}},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),e=d.length,f=d.shift(),g=c._queueHooks(a,b),h=function(){c.dequeue(a,b)};if(f==="inprogress"){f=d.shift();e--}if(g.cur=f){b==="fx"&&d.unshift("inprogress");delete g.stop;f.call(a,h,g)}!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var d=b+"queueHooks";return c._data(a,d)||c._data(a,d,{empty:c.Callbacks("once memory").add(function(){c._removeData(a,b+"queue");
c._removeData(a,d)})})}});c.fn.extend({queue:function(a,b){var d=2;if(typeof a!=="string"){b=a;a="fx";d--}if(arguments.length<d)return c.queue(this[0],a);return b===t?this:this.each(function(){var e=c.queue(this,a,b);c._queueHooks(this,a);a==="fx"&&e[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,function(d,e){var f=setTimeout(d,a);e.stop=function(){clearTimeout(f)}})},
clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var d,e=1,f=c.Deferred(),g=this,h=this.length,j=function(){--e||f.resolveWith(g,[g])};if(typeof a!=="string"){b=a;a=t}for(a=a||"fx";h--;)if((d=c._data(g[h],a+"queueHooks"))&&d.empty){e++;d.empty.add(j)}j();return f.promise(b)}});var Ba,Zb,fb=/[\t\r\n]/g,Sc=/\r/g,Tc=/^(?:input|select|textarea|button|object)$/i,Uc=/^(?:a|area)$/i,$b=/^(?:checked|selected|autofocus|autoplay|async|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped)$/i,
gb=/^(?:checked|selected)$/i,ta=c.support.getSetAttribute,hb=c.support.input;c.fn.extend({attr:function(a,b){return c.access(this,c.attr,a,b,arguments.length>1)},removeAttr:function(a){return this.each(function(){c.removeAttr(this,a)})},prop:function(a,b){return c.access(this,c.prop,a,b,arguments.length>1)},removeProp:function(a){a=c.propFix[a]||a;return this.each(function(){try{this[a]=t;delete this[a]}catch(b){}})},addClass:function(a){var b,d,e,f,g,h=0,j=this.length;b=typeof a==="string"&&a;if(c.isFunction(a))return this.each(function(m){c(this).addClass(a.call(this,
m,this.className))});if(b)for(b=(a||"").match(ja)||[];h<j;h++){d=this[h];if(e=d.nodeType===1&&(d.className?(" "+d.className+" ").replace(fb," "):" ")){for(g=0;f=b[g++];)if(e.indexOf(" "+f+" ")<0)e+=f+" ";d.className=c.trim(e)}}return this},removeClass:function(a){var b,d,e,f,g,h=0,j=this.length;b=arguments.length===0||typeof a==="string"&&a;if(c.isFunction(a))return this.each(function(m){c(this).removeClass(a.call(this,m,this.className))});if(b)for(b=(a||"").match(ja)||[];h<j;h++){d=this[h];if(e=
d.nodeType===1&&(d.className?(" "+d.className+" ").replace(fb," "):"")){for(g=0;f=b[g++];)for(;e.indexOf(" "+f+" ")>=0;)e=e.replace(" "+f+" "," ");d.className=a?c.trim(e):""}}return this},toggleClass:function(a,b){var d=typeof a,e=typeof b==="boolean";if(c.isFunction(a))return this.each(function(f){c(this).toggleClass(a.call(this,f,this.className,b),b)});return this.each(function(){if(d==="string")for(var f,g=0,h=c(this),j=b,m=a.match(ja)||[];f=m[g++];){j=e?j:!h.hasClass(f);h[j?"addClass":"removeClass"](f)}else if(d===
"undefined"||d==="boolean"){this.className&&c._data(this,"__className__",this.className);this.className=this.className||a===false?"":c._data(this,"__className__")||""}})},hasClass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1&&(" "+this[b].className+" ").replace(fb," ").indexOf(a)>=0)return true;return false},val:function(a){var b,d,e,f=this[0];if(arguments.length){e=c.isFunction(a);return this.each(function(g){var h=c(this);if(this.nodeType===1){g=e?a.call(this,
g,h.val()):a;if(g==null)g="";else if(typeof g==="number")g+="";else if(c.isArray(g))g=c.map(g,function(j){return j==null?"":j+""});b=c.valHooks[this.type]||c.valHooks[this.nodeName.toLowerCase()];if(!b||!("set"in b)||b.set(this,g,"value")===t)this.value=g}})}else if(f){if((b=c.valHooks[f.type]||c.valHooks[f.nodeName.toLowerCase()])&&"get"in b&&(d=b.get(f,"value"))!==t)return d;d=f.value;return typeof d==="string"?d.replace(Sc,""):d==null?"":d}}});c.extend({valHooks:{option:{get:function(a){var b=
a.attributes.value;return!b||b.specified?a.value:a.text}},select:{get:function(a){for(var b,d=a.options,e=a.selectedIndex,f=(a=a.type==="select-one"||e<0)?null:[],g=a?e+1:d.length,h=e<0?g:a?e:0;h<g;h++){b=d[h];if((b.selected||h===e)&&(c.support.optDisabled?!b.disabled:b.getAttribute("disabled")===null)&&(!b.parentNode.disabled||!c.nodeName(b.parentNode,"optgroup"))){b=c(b).val();if(a)return b;f.push(b)}}return f},set:function(a,b){var d=c.makeArray(b);c(a).find("option").each(function(){this.selected=
c.inArray(c(this).val(),d)>=0});if(!d.length)a.selectedIndex=-1;return d}}},attr:function(a,b,d){var e,f,g;g=a.nodeType;if(!(!a||g===3||g===8||g===2)){if(typeof a.getAttribute==="undefined")return c.prop(a,b,d);if(g=g!==1||!c.isXMLDoc(a)){b=b.toLowerCase();f=c.attrHooks[b]||($b.test(b)?Zb:Ba)}if(d!==t)if(d===null)c.removeAttr(a,b);else if(f&&g&&"set"in f&&(e=f.set(a,d,b))!==t)return e;else{a.setAttribute(b,d+"");return d}else if(f&&g&&"get"in f&&(e=f.get(a,b))!==null)return e;else{if(typeof a.getAttribute!==
"undefined")e=a.getAttribute(b);return e==null?t:e}}},removeAttr:function(a,b){var d,e,f=0,g=b&&b.match(ja);if(g&&a.nodeType===1)for(;d=g[f++];){e=c.propFix[d]||d;if($b.test(d))if(!ta&&gb.test(d))a[c.camelCase("default-"+d)]=a[e]=false;else a[e]=false;else c.attr(a,d,"");a.removeAttribute(ta?d:e)}},attrHooks:{type:{set:function(a,b){if(!c.support.radioValue&&b==="radio"&&c.nodeName(a,"input")){var d=a.value;a.setAttribute("type",b);if(d)a.value=d;return b}}}},propFix:{tabindex:"tabIndex",readonly:"readOnly",
"for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},prop:function(a,b,d){var e,f,g=a.nodeType;if(!(!a||g===3||g===8||g===2)){if(g!==1||!c.isXMLDoc(a)){b=c.propFix[b]||b;f=c.propHooks[b]}return d!==t?f&&"set"in f&&(e=f.set(a,d,b))!==t?e:a[b]=d:f&&"get"in f&&(e=f.get(a,b))!==null?e:a[b]}},propHooks:{tabIndex:{get:function(a){var b=
a.getAttributeNode("tabindex");return b&&b.specified?parseInt(b.value,10):Tc.test(a.nodeName)||Uc.test(a.nodeName)&&a.href?0:t}}}});Zb={get:function(a,b){var d=c.prop(a,b),e=typeof d==="boolean"&&a.getAttribute(b);return(d=typeof d==="boolean"?hb&&ta?e!=null:gb.test(b)?a[c.camelCase("default-"+b)]:!!e:a.getAttributeNode(b))&&d.value!==false?b.toLowerCase():t},set:function(a,b,d){if(b===false)c.removeAttr(a,d);else if(hb&&ta||!gb.test(d))a.setAttribute(!ta&&c.propFix[d]||d,d);else a[c.camelCase("default-"+
d)]=a[d]=true;return d}};if(!hb||!ta)c.attrHooks.value={get:function(a,b){var d=a.getAttributeNode(b);return c.nodeName(a,"input")?a.defaultValue:d&&d.specified?d.value:t},set:function(a,b,d){if(c.nodeName(a,"input"))a.defaultValue=b;else return Ba&&Ba.set(a,b,d)}};if(!ta){Ba=c.valHooks.button={get:function(a,b){var d=a.getAttributeNode(b);return d&&(b==="id"||b==="name"||b==="coords"?d.value!=="":d.specified)?d.value:t},set:function(a,b,d){var e=a.getAttributeNode(d);e||a.setAttributeNode(e=a.ownerDocument.createAttribute(d));
e.value=b+="";return d==="value"||b===a.getAttribute(d)?b:t}};c.attrHooks.contenteditable={get:Ba.get,set:function(a,b,d){Ba.set(a,b===""?false:b,d)}};c.each(["width","height"],function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{set:function(d,e){if(e===""){d.setAttribute(b,"auto");return e}}})})}if(!c.support.hrefNormalized){c.each(["href","src","width","height"],function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{get:function(d){d=d.getAttribute(b,2);return d==null?t:d}})});c.each(["href","src"],
function(a,b){c.propHooks[b]={get:function(d){return d.getAttribute(b,4)}}})}if(!c.support.style)c.attrHooks.style={get:function(a){return a.style.cssText||t},set:function(a,b){return a.style.cssText=b+""}};if(!c.support.optSelected)c.propHooks.selected=c.extend(c.propHooks.selected,{get:function(){return null}});if(!c.support.enctype)c.propFix.enctype="encoding";c.support.checkOn||c.each(["radio","checkbox"],function(){c.valHooks[this]={get:function(a){return a.getAttribute("value")===null?"on":
a.value}}});c.each(["radio","checkbox"],function(){c.valHooks[this]=c.extend(c.valHooks[this],{set:function(a,b){if(c.isArray(b))return a.checked=c.inArray(c(a).val(),b)>=0}})});var ib=/^(?:input|select|textarea)$/i,Vc=/^key/,Wc=/^(?:mouse|contextmenu)|click/,ac=/^(?:focusinfocus|focusoutblur)$/,bc=/^([^.]*)(?:\.(.+)|)$/;c.event={global:{},add:function(a,b,d,e,f){var g,h,j,m,p,r,n,v,y;if(p=a.nodeType!==3&&a.nodeType!==8&&c._data(a)){if(d.handler){g=d;d=g.handler;f=g.selector}if(!d.guid)d.guid=c.guid++;
if(!(m=p.events))m=p.events={};if(!(h=p.handle)){h=p.handle=function(O){return typeof c!=="undefined"&&(!O||c.event.triggered!==O.type)?c.event.dispatch.apply(h.elem,arguments):t};h.elem=a}b=(b||"").match(ja)||[""];for(p=b.length;p--;){j=bc.exec(b[p])||[];v=r=j[1];y=(j[2]||"").split(".").sort();j=c.event.special[v]||{};v=(f?j.delegateType:j.bindType)||v;j=c.event.special[v]||{};r=c.extend({type:v,origType:r,data:e,handler:d,guid:d.guid,selector:f,needsContext:f&&c.expr.match.needsContext.test(f),
namespace:y.join(".")},g);if(!(n=m[v])){n=m[v]=[];n.delegateCount=0;if(!j.setup||j.setup.call(a,e,y,h)===false)if(a.addEventListener)a.addEventListener(v,h,false);else a.attachEvent&&a.attachEvent("on"+v,h)}if(j.add){j.add.call(a,r);if(!r.handler.guid)r.handler.guid=d.guid}f?n.splice(n.delegateCount++,0,r):n.push(r);c.event.global[v]=true}a=null}},remove:function(a,b,d,e,f){var g,h,j,m,p,r,n,v,y,O,X,V=c.hasData(a)&&c._data(a);if(V&&(m=V.events)){b=(b||"").match(ja)||[""];for(p=b.length;p--;){j=bc.exec(b[p])||
[];y=X=j[1];O=(j[2]||"").split(".").sort();if(y){n=c.event.special[y]||{};y=(e?n.delegateType:n.bindType)||y;v=m[y]||[];j=j[2]&&RegExp("(^|\\.)"+O.join("\\.(?:.*\\.|)")+"(\\.|$)");for(h=g=v.length;g--;){r=v[g];if((f||X===r.origType)&&(!d||d.guid===r.guid)&&(!j||j.test(r.namespace))&&(!e||e===r.selector||e==="**"&&r.selector)){v.splice(g,1);r.selector&&v.delegateCount--;n.remove&&n.remove.call(a,r)}}if(h&&!v.length){if(!n.teardown||n.teardown.call(a,O,V.handle)===false)c.removeEvent(a,y,V.handle);
delete m[y]}}else for(y in m)c.event.remove(a,y+b[p],d,e,true)}if(c.isEmptyObject(m)){delete V.handle;c._removeData(a,"events")}}},trigger:function(a,b,d,e){var f,g,h,j,m,p,r=[d||A],n=a.type||a;p=a.namespace?a.namespace.split("."):[];g=f=d=d||A;if(!(d.nodeType===3||d.nodeType===8))if(!ac.test(n+c.event.triggered)){if(n.indexOf(".")>=0){p=n.split(".");n=p.shift();p.sort()}j=n.indexOf(":")<0&&"on"+n;a=a[c.expando]?a:new c.Event(n,typeof a==="object"&&a);a.isTrigger=true;a.namespace=p.join(".");a.namespace_re=
a.namespace?RegExp("(^|\\.)"+p.join("\\.(?:.*\\.|)")+"(\\.|$)"):null;a.result=t;if(!a.target)a.target=d;b=b==null?[a]:c.makeArray(b,[a]);p=c.event.special[n]||{};if(!(!e&&p.trigger&&p.trigger.apply(d,b)===false)){if(!e&&!p.noBubble&&!c.isWindow(d)){h=p.delegateType||n;if(!ac.test(h+n))g=g.parentNode;for(;g;g=g.parentNode){r.push(g);f=g}if(f===(d.ownerDocument||A))r.push(f.defaultView||f.parentWindow||C)}for(f=0;(g=r[f++])&&!a.isPropagationStopped();){a.type=f>1?h:p.bindType||n;(m=(c._data(g,"events")||
{})[a.type]&&c._data(g,"handle"))&&m.apply(g,b);(m=j&&g[j])&&c.acceptData(g)&&m.apply&&m.apply(g,b)===false&&a.preventDefault()}a.type=n;if(!e&&!a.isDefaultPrevented())if((!p._default||p._default.apply(d.ownerDocument,b)===false)&&!(n==="click"&&c.nodeName(d,"a"))&&c.acceptData(d))if(j&&d[n]&&!c.isWindow(d)){if(f=d[j])d[j]=null;c.event.triggered=n;try{d[n]()}catch(v){}c.event.triggered=t;if(f)d[j]=f}return a.result}}},dispatch:function(a){a=c.event.fix(a);var b,d,e,f,g=[],h=sa.call(arguments);b=(c._data(this,
"events")||{})[a.type]||[];var j=c.event.special[a.type]||{};h[0]=a;a.delegateTarget=this;if(!(j.preDispatch&&j.preDispatch.call(this,a)===false)){g=c.event.handlers.call(this,a,b);for(b=0;(f=g[b++])&&!a.isPropagationStopped();){a.currentTarget=f.elem;for(d=0;(e=f.handlers[d++])&&!a.isImmediatePropagationStopped();)if(!a.namespace_re||a.namespace_re.test(e.namespace)){a.handleObj=e;a.data=e.data;e=((c.event.special[e.origType]||{}).handle||e.handler).apply(f.elem,h);if(e!==t)if((a.result=e)===false){a.preventDefault();
a.stopPropagation()}}}j.postDispatch&&j.postDispatch.call(this,a);return a.result}},handlers:function(a,b){var d,e,f,g,h=[],j=b.delegateCount,m=a.target;if(j&&m.nodeType&&(!a.button||a.type!=="click"))for(;m!=this;m=m.parentNode||this)if(m.disabled!==true||a.type!=="click"){e=[];for(d=0;d<j;d++){g=b[d];f=g.selector+" ";if(e[f]===t)e[f]=g.needsContext?c(f,this).index(m)>=0:c.find(f,this,null,[m]).length;e[f]&&e.push(g)}e.length&&h.push({elem:m,handlers:e})}j<b.length&&h.push({elem:this,handlers:b.slice(j)});
return h},fix:function(a){if(a[c.expando])return a;var b,d,e=a,f=c.event.fixHooks[a.type]||{},g=f.props?this.props.concat(f.props):this.props;a=new c.Event(e);for(b=g.length;b--;){d=g[b];a[d]=e[d]}if(!a.target)a.target=e.srcElement||A;if(a.target.nodeType===3)a.target=a.target.parentNode;a.metaKey=!!a.metaKey;return f.filter?f.filter(a,e):a},props:"altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),fixHooks:{},keyHooks:{props:"char charCode key keyCode".split(" "),
filter:function(a,b){if(a.which==null)a.which=b.charCode!=null?b.charCode:b.keyCode;return a}},mouseHooks:{props:"button buttons clientX clientY fromElement offsetX offsetY pageX pageY screenX screenY toElement".split(" "),filter:function(a,b){var d,e,f=b.button,g=b.fromElement;if(a.pageX==null&&b.clientX!=null){d=a.target.ownerDocument||A;e=d.documentElement;d=d.body;a.pageX=b.clientX+(e&&e.scrollLeft||d&&d.scrollLeft||0)-(e&&e.clientLeft||d&&d.clientLeft||0);a.pageY=b.clientY+(e&&e.scrollTop||d&&
d.scrollTop||0)-(e&&e.clientTop||d&&d.clientTop||0)}if(!a.relatedTarget&&g)a.relatedTarget=g===a.target?b.toElement:g;if(!a.which&&f!==t)a.which=f&1?1:f&2?3:f&4?2:0;return a}},special:{load:{noBubble:true},click:{trigger:function(){if(c.nodeName(this,"input")&&this.type==="checkbox"&&this.click){this.click();return false}}},focus:{trigger:function(){if(this!==A.activeElement&&this.focus)try{this.focus();return false}catch(a){}},delegateType:"focusin"},blur:{trigger:function(){if(this===A.activeElement&&
this.blur){this.blur();return false}},delegateType:"focusout"},beforeunload:{postDispatch:function(a){if(a.result!==t)a.originalEvent.returnValue=a.result}}},simulate:function(a,b,d,e){a=c.extend(new c.Event,d,{type:a,isSimulated:true,originalEvent:{}});e?c.event.trigger(a,null,b):c.event.dispatch.call(b,a);a.isDefaultPrevented()&&d.preventDefault()}};c.removeEvent=A.removeEventListener?function(a,b,d){a.removeEventListener&&a.removeEventListener(b,d,false)}:function(a,b,d){b="on"+b;if(a.detachEvent){if(typeof a[b]===
"undefined")a[b]=null;a.detachEvent(b,d)}};c.Event=function(a,b){if(!(this instanceof c.Event))return new c.Event(a,b);if(a&&a.type){this.originalEvent=a;this.type=a.type;this.isDefaultPrevented=a.defaultPrevented||a.returnValue===false||a.getPreventDefault&&a.getPreventDefault()?Ka:ya}else this.type=a;b&&c.extend(this,b);this.timeStamp=a&&a.timeStamp||c.now();this[c.expando]=true};c.Event.prototype={isDefaultPrevented:ya,isPropagationStopped:ya,isImmediatePropagationStopped:ya,preventDefault:function(){var a=
this.originalEvent;this.isDefaultPrevented=Ka;if(a)if(a.preventDefault)a.preventDefault();else a.returnValue=false},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=Ka;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=Ka;this.stopPropagation()}};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={delegateType:b,bindType:b,handle:function(d){var e,
f=d.relatedTarget,g=d.handleObj;if(!f||f!==this&&!c.contains(this,f)){d.type=g.origType;e=g.handler.apply(this,arguments);d.type=b}return e}}});if(!c.support.submitBubbles)c.event.special.submit={setup:function(){if(c.nodeName(this,"form"))return false;c.event.add(this,"click._submit keypress._submit",function(a){a=a.target;if((a=c.nodeName(a,"input")||c.nodeName(a,"button")?a.form:t)&&!c._data(a,"submitBubbles")){c.event.add(a,"submit._submit",function(b){b._submit_bubble=true});c._data(a,"submitBubbles",
true)}})},postDispatch:function(a){if(a._submit_bubble){delete a._submit_bubble;this.parentNode&&!a.isTrigger&&c.event.simulate("submit",this.parentNode,a,true)}},teardown:function(){if(c.nodeName(this,"form"))return false;c.event.remove(this,"._submit")}};if(!c.support.changeBubbles)c.event.special.change={setup:function(){if(ib.test(this.nodeName)){if(this.type==="checkbox"||this.type==="radio"){c.event.add(this,"propertychange._change",function(a){if(a.originalEvent.propertyName==="checked")this._just_changed=
true});c.event.add(this,"click._change",function(a){if(this._just_changed&&!a.isTrigger)this._just_changed=false;c.event.simulate("change",this,a,true)})}return false}c.event.add(this,"beforeactivate._change",function(a){a=a.target;if(ib.test(a.nodeName)&&!c._data(a,"changeBubbles")){c.event.add(a,"change._change",function(b){this.parentNode&&!b.isSimulated&&!b.isTrigger&&c.event.simulate("change",this.parentNode,b,true)});c._data(a,"changeBubbles",true)}})},handle:function(a){var b=a.target;if(this!==
b||a.isSimulated||a.isTrigger||b.type!=="radio"&&b.type!=="checkbox")return a.handleObj.handler.apply(this,arguments)},teardown:function(){c.event.remove(this,"._change");return!ib.test(this.nodeName)}};c.support.focusinBubbles||c.each({focus:"focusin",blur:"focusout"},function(a,b){var d=0,e=function(f){c.event.simulate(b,f.target,c.event.fix(f),true)};c.event.special[b]={setup:function(){d++===0&&A.addEventListener(a,e,true)},teardown:function(){--d===0&&A.removeEventListener(a,e,true)}}});c.fn.extend({on:function(a,
b,d,e,f){var g,h;if(typeof a==="object"){if(typeof b!=="string"){d=d||b;b=t}for(h in a)this.on(h,b,d,a[h],f);return this}if(d==null&&e==null){e=b;d=b=t}else if(e==null)if(typeof b==="string"){e=d;d=t}else{e=d;d=b;b=t}if(e===false)e=ya;else if(!e)return this;if(f===1){g=e;e=function(j){c().off(j);return g.apply(this,arguments)};e.guid=g.guid||(g.guid=c.guid++)}return this.each(function(){c.event.add(this,a,e,d,b)})},one:function(a,b,d,e){return this.on(a,b,d,e,1)},off:function(a,b,d){var e;if(a&&a.preventDefault&&
a.handleObj){e=a.handleObj;c(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler);return this}if(typeof a==="object"){for(e in a)this.off(e,b,a[e]);return this}if(b===false||typeof b==="function"){d=b;b=t}if(d===false)d=ya;return this.each(function(){c.event.remove(this,a,d,b)})},bind:function(a,b,d){return this.on(a,null,b,d)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,d,e){return this.on(b,a,d,e)},undelegate:function(a,b,d){return arguments.length===
1?this.off(a,"**"):this.off(b,a||"**",d)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){var d=this[0];if(d)return c.event.trigger(a,b,d,true)},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),function(a,
b){c.fn[b]=function(d,e){return arguments.length>0?this.on(b,null,d,e):this.trigger(b)};if(Vc.test(b))c.event.fixHooks[b]=c.event.keyHooks;if(Wc.test(b))c.event.fixHooks[b]=c.event.mouseHooks});(function(a,b){function d(i){return Xc.test(i+"")}function e(){var i,l=[];return i=function(k,o){if(l.push(k+=" ")>D.cacheLength)delete i[l.shift()];return i[k]=o}}function f(i){i[H]=true;return i}function g(i){var l=M.createElement("div");try{return i(l)}catch(k){return false}finally{}}function h(i,l,k,o){var q,
u,s,w,x;if((l?l.ownerDocument||l:ga)!==M)Y(l);l=l||M;k=k||[];if(!i||typeof i!=="string")return k;if((w=l.nodeType)!==1&&w!==9)return[];if(!J&&!o){if(q=Yc.exec(i))if(s=q[1])if(w===9)if((u=l.getElementById(s))&&u.parentNode){if(u.id===s){k.push(u);return k}}else return k;else{if(l.ownerDocument&&(u=l.ownerDocument.getElementById(s))&&ha(l,u)&&u.id===s){k.push(u);return k}}else if(q[2]){Ca.apply(k,Da.call(l.getElementsByTagName(i),0));return k}else if((s=q[3])&&F.getByClassName&&l.getElementsByClassName){Ca.apply(k,
Da.call(l.getElementsByClassName(s),0));return k}if(F.qsa&&!Z.test(i)){q=true;u=H;s=l;x=w===9&&i;if(w===1&&l.nodeName.toLowerCase()!=="object"){w=n(i);if(q=l.getAttribute("id"))u=q.replace(Zc,"\\$&");else l.setAttribute("id",u);u="[id='"+u+"'] ";for(s=w.length;s--;)w[s]=u+v(w[s]);s=jb.test(i)&&l.parentNode||l;x=w.join(",")}if(x)try{Ca.apply(k,Da.call(s.querySelectorAll(x),0));return k}catch(K){}finally{q||l.removeAttribute("id")}}}var z;a:{i=i.replace(Sa,"$1");l=l;k=k;o=o;u=n(i);if(!o)if(u.length===
1){q=u[0]=u[0].slice(0);if(q.length>2&&(z=q[0]).type==="ID"&&l.nodeType===9&&!J&&D.relative[q[1].type]){l=D.find.ID(z.matches[0].replace(ma,na),l)[0];if(!l){z=k;break a}i=i.slice(q.shift().value.length)}for(w=Ta.needsContext.test(i)?-1:q.length-1;w>=0;w--){z=q[w];if(D.relative[s=z.type])break;if(s=D.find[s])if(o=s(z.matches[0].replace(ma,na),jb.test(q[0].type)&&l.parentNode||l)){q.splice(w,1);i=o.length&&v(q);if(!i){Ca.apply(k,Da.call(o,0));z=k;break a}break}}}P(i,u)(o,l,J,k,jb.test(i));z=k}return z}
function j(i,l){for(var k=i&&l&&i.nextSibling;k;k=k.nextSibling)if(k===l)return-1;return i?1:-1}function m(i){return function(l){return l.nodeName.toLowerCase()==="input"&&l.type===i}}function p(i){return function(l){var k=l.nodeName.toLowerCase();return(k==="input"||k==="button")&&l.type===i}}function r(i){return f(function(l){l=+l;return f(function(k,o){for(var q,u=i([],k.length,l),s=u.length;s--;)if(k[q=u[s]])k[q]=!(o[q]=k[q])})})}function n(i,l){var k,o,q,u,s,w,x;if(s=cc[i+" "])return l?0:s.slice(0);
s=i;w=[];for(x=D.preFilter;s;){if(!k||(o=$c.exec(s))){if(o)s=s.slice(o[0].length)||s;w.push(q=[])}k=false;if(o=ad.exec(s)){k=o.shift();q.push({value:k,type:o[0].replace(Sa," ")});s=s.slice(k.length)}for(u in D.filter)if((o=Ta[u].exec(s))&&(!x[u]||(o=x[u](o)))){k=o.shift();q.push({value:k,type:u,matches:o});s=s.slice(k.length)}if(!k)break}return l?s.length:s?h.error(i):cc(i,w).slice(0)}function v(i){for(var l=0,k=i.length,o="";l<k;l++)o+=i[l].value;return o}function y(i,l,k){var o=l.dir,q=k&&l.dir===
"parentNode",u=kb++;return l.first?function(s,w,x){for(;s=s[o];)if(s.nodeType===1||q)return i(s,w,x)}:function(s,w,x){var K,z,I,E=ca+" "+u;if(x)for(;s=s[o];){if(s.nodeType===1||q)if(i(s,w,x))return true}else for(;s=s[o];)if(s.nodeType===1||q){I=s[H]||(s[H]={});if((z=I[o])&&z[0]===E){if((K=z[1])===true||K===B)return K===true}else{z=I[o]=[E];z[1]=i(s,w,x)||B;if(z[1]===true)return true}}}}function O(i){return i.length>1?function(l,k,o){for(var q=i.length;q--;)if(!i[q](l,k,o))return false;return true}:
i[0]}function X(i,l,k,o,q){for(var u,s=[],w=0,x=i.length,K=l!=null;w<x;w++)if(u=i[w])if(!k||k(u,o,q)){s.push(u);K&&l.push(w)}return s}function V(i,l,k,o,q,u){if(o&&!o[H])o=V(o);if(q&&!q[H])q=V(q,u);return f(function(s,w,x,K){var z,I,E=[],Q=[],$=w.length,N;if(!(N=s)){N=l||"*";for(var L=x.nodeType?[x]:x,ia=[],Ea=0,lb=L.length;Ea<lb;Ea++)h(N,L[Ea],ia);N=ia}N=N;N=i&&(s||!l)?X(N,E,i,x,K):N;L=k?q||(s?i:$||o)?[]:w:N;k&&k(N,L,x,K);if(o){z=X(L,Q);o(z,[],x,K);for(x=z.length;x--;)if(I=z[x])L[Q[x]]=!(N[Q[x]]=
I)}if(s){if(q||i){if(q){z=[];for(x=L.length;x--;)if(I=L[x])z.push(N[x]=I);q(null,L=[],z,K)}for(x=L.length;x--;)if((I=L[x])&&(z=q?mb.call(s,I):E[x])>-1)s[z]=!(w[z]=I)}}else{L=X(L===w?L.splice($,L.length):L);q?q(null,w,L,K):Ca.apply(w,L)}})}function Fa(i){var l,k,o,q=i.length,u=D.relative[i[0].type];k=u||D.relative[" "];for(var s=u?1:0,w=y(function(z){return z===l},k,true),x=y(function(z){return mb.call(l,z)>-1},k,true),K=[function(z,I,E){return!u&&(E||I!==T)||((l=I).nodeType?w(z,I,E):x(z,I,E))}];s<
q;s++)if(k=D.relative[i[s].type])K=[y(O(K),k)];else{k=D.filter[i[s].type].apply(null,i[s].matches);if(k[H]){for(o=++s;o<q;o++)if(D.relative[i[o].type])break;return V(s>1&&O(K),s>1&&v(i.slice(0,s-1)).replace(Sa,"$1"),k,s<o&&Fa(i.slice(s,o)),o<q&&Fa(i=i.slice(o)),o<q&&v(i))}K.push(k)}return O(K)}function Ua(i,l){var k=0,o=l.length>0,q=i.length>0,u=function(s,w,x,K,z){var I,E,Q=[],$=0,N="0",L=s&&[],ia=z!=null,Ea=T,lb=s||q&&D.find.TAG("*",z&&w.parentNode||w),dc=ca+=Ea==null?1:Math.E;if(ia){T=w!==M&&w;
B=k}for(;(z=lb[N])!=null;N++){if(q&&z){for(I=0;E=i[I];I++)if(E(z,w,x)){K.push(z);break}if(ia){ca=dc;B=++k}}if(o){if(z=!E&&z)$--;s&&L.push(z)}}$+=N;if(o&&N!==$){for(I=0;E=l[I];I++)E(L,Q,w,x);if(s){if($>0)for(;N--;)L[N]||Q[N]||(Q[N]=bd.call(K));Q=X(Q)}Ca.apply(K,Q);ia&&!s&&Q.length>0&&$+l.length>1&&h.uniqueSort(K)}if(ia){ca=dc;T=Ea}return L};return o?f(u):u}function da(){}var ka,B,D,G,W,P,fa,T,Y,M,R,J,Z,S,U,ha,ua,H="sizzle"+-new Date,ga=a.document,F={},ca=0,kb=0,ec=e(),cc=e(),fc=e(),la=typeof b,va=
[],bd=va.pop,Ca=va.push,Da=va.slice,mb=va.indexOf||function(i){for(var l=0,k=this.length;l<k;l++)if(this[l]===i)return l;return-1};va="(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w#");var gc="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+va+")|)|)[\\x20\\t\\r\\n\\f]*\\]",nb=":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\(((['\"])((?:\\\\.|[^\\\\])*?)\\3|((?:\\\\.|[^\\\\()[\\]]|"+gc.replace(3,8)+")*)|.*)\\)|)",
Sa=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),$c=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,ad=/^[\x20\t\r\n\f]*([\x20\t\r\n\f>+~])[\x20\t\r\n\f]*/,cd=RegExp(nb),dd=RegExp("^"+va+"$"),Ta={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,NAME:/^\[name=['"]?((?:\\.|[\w-]|[^\x00-\xa0])+)['"]?\]/,TAG:RegExp("^("+"(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:RegExp("^"+gc),PSEUDO:RegExp("^"+nb),CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)",
"i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)","i")},jb=/[\x20\t\r\n\f]*[+~]/,Xc=/\{\s*\[native code\]\s*\}/,Yc=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ed=/^(?:input|select|textarea|button)$/i,fd=/^h\d$/i,Zc=/'|\\/g,gd=/\=[\x20\t\r\n\f]*([^'"\]]*)[\x20\t\r\n\f]*\]/g,ma=/\\([\da-fA-F]{1,6}[\x20\t\r\n\f]?|.)/g,na=function(i,l){var k="0x"+l-65536;return k!==k?l:k<0?String.fromCharCode(k+
65536):String.fromCharCode(k>>10|55296,k&1023|56320)};try{Da.call(R.childNodes,0)}catch(Ed){Da=function(i){for(var l,k=[];l=this[i];i++)k.push(l);return k}}W=h.isXML=function(i){return(i=i&&(i.ownerDocument||i).documentElement)?i.nodeName!=="HTML":false};Y=h.setDocument=function(i){var l=i?i.ownerDocument||i:ga;if(l===M||l.nodeType!==9||!l.documentElement)return M;M=l;R=l.documentElement;J=W(l);F.tagNameNoComments=g(function(k){k.appendChild(l.createComment(""));return!k.getElementsByTagName("*").length});
F.attributes=g(function(k){k.innerHTML="<select></select>";k=typeof k.lastChild.getAttribute("multiple");return k!=="boolean"&&k!=="string"});F.getByClassName=g(function(k){k.innerHTML="<div class='hidden e'></div><div class='hidden'></div>";if(!k.getElementsByClassName||!k.getElementsByClassName("e").length)return false;k.lastChild.className="e";return k.getElementsByClassName("e").length===2});F.getByName=g(function(k){k.id=H+0;k.innerHTML="<a name='"+H+"'></a><div name='"+H+"'></div>";R.insertBefore(k,
R.firstChild);var o=l.getElementsByName&&l.getElementsByName(H).length===2+l.getElementsByName(H+0).length;F.getIdNotName=!l.getElementById(H);R.removeChild(k);return o});D.attrHandle=g(function(k){k.innerHTML="<a href='#'></a>";return k.firstChild&&typeof k.firstChild.getAttribute!==la&&k.firstChild.getAttribute("href")==="#"})?{}:{href:function(k){return k.getAttribute("href",2)},type:function(k){return k.getAttribute("type")}};if(F.getIdNotName){D.find.ID=function(k,o){if(typeof o.getElementById!==
la&&!J){var q=o.getElementById(k);return q&&q.parentNode?[q]:[]}};D.filter.ID=function(k){var o=k.replace(ma,na);return function(q){return q.getAttribute("id")===o}}}else{D.find.ID=function(k,o){if(typeof o.getElementById!==la&&!J){var q=o.getElementById(k);return q?q.id===k||typeof q.getAttributeNode!==la&&q.getAttributeNode("id").value===k?[q]:b:[]}};D.filter.ID=function(k){var o=k.replace(ma,na);return function(q){return(q=typeof q.getAttributeNode!==la&&q.getAttributeNode("id"))&&q.value===o}}}D.find.TAG=
F.tagNameNoComments?function(k,o){if(typeof o.getElementsByTagName!==la)return o.getElementsByTagName(k)}:function(k,o){var q,u=[],s=0,w=o.getElementsByTagName(k);if(k==="*"){for(;q=w[s];s++)q.nodeType===1&&u.push(q);return u}return w};D.find.NAME=F.getByName&&function(k,o){if(typeof o.getElementsByName!==la)return o.getElementsByName(name)};D.find.CLASS=F.getByClassName&&function(k,o){if(typeof o.getElementsByClassName!==la&&!J)return o.getElementsByClassName(k)};S=[];Z=[":focus"];if(F.qsa=d(l.querySelectorAll)){g(function(k){k.innerHTML=
"<select><option selected=''></option></select>";k.querySelectorAll("[selected]").length||Z.push("\\[[\\x20\\t\\r\\n\\f]*(?:checked|disabled|ismap|multiple|readonly|selected|value)");k.querySelectorAll(":checked").length||Z.push(":checked")});g(function(k){k.innerHTML="<input type='hidden' i=''/>";k.querySelectorAll("[i^='']").length&&Z.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:\"\"|'')");k.querySelectorAll(":enabled").length||Z.push(":enabled",":disabled");k.querySelectorAll("*,:x");Z.push(",.*:")})}if(F.matchesSelector=
d(U=R.matchesSelector||R.mozMatchesSelector||R.webkitMatchesSelector||R.oMatchesSelector||R.msMatchesSelector))g(function(k){F.disconnectedMatch=U.call(k,"div");U.call(k,"[s!='']:x");S.push("!=",nb)});Z=RegExp(Z.join("|"));S=RegExp(S.join("|"));ha=d(R.contains)||R.compareDocumentPosition?function(k,o){var q=k.nodeType===9?k.documentElement:k,u=o&&o.parentNode;return k===u||!!(u&&u.nodeType===1&&(q.contains?q.contains(u):k.compareDocumentPosition&&k.compareDocumentPosition(u)&16))}:function(k,o){if(o)for(;o=
o.parentNode;)if(o===k)return true;return false};ua=R.compareDocumentPosition?function(k,o){var q;if(k===o){fa=true;return 0}if(q=o.compareDocumentPosition&&k.compareDocumentPosition&&k.compareDocumentPosition(o)){if(q&1||k.parentNode&&k.parentNode.nodeType===11){if(k===l||ha(ga,k))return-1;if(o===l||ha(ga,o))return 1;return 0}return q&4?-1:1}return k.compareDocumentPosition?-1:1}:function(k,o){var q,u=0;q=k.parentNode;var s=o.parentNode,w=[k],x=[o];if(k===o){fa=true;return 0}else if(k.sourceIndex&&
o.sourceIndex)return(~o.sourceIndex||-2147483648)-(ha(ga,k)&&~k.sourceIndex||-2147483648);else if(!q||!s)return k===l?-1:o===l?1:q?-1:s?1:0;else if(q===s)return j(k,o);for(q=k;q=q.parentNode;)w.unshift(q);for(q=o;q=q.parentNode;)x.unshift(q);for(;w[u]===x[u];)u++;return u?j(w[u],x[u]):w[u]===ga?-1:x[u]===ga?1:0};fa=false;[0,0].sort(ua);F.detectDuplicates=fa;return M};h.matches=function(i,l){return h(i,null,null,l)};h.matchesSelector=function(i,l){if((i.ownerDocument||i)!==M)Y(i);l=l.replace(gd,"='$1']");
if(F.matchesSelector&&!J&&(!S||!S.test(l))&&!Z.test(l))try{var k=U.call(i,l);if(k||F.disconnectedMatch||i.document&&i.document.nodeType!==11)return k}catch(o){}return h(l,M,null,[i]).length>0};h.contains=function(i,l){if((i.ownerDocument||i)!==M)Y(i);return ha(i,l)};h.attr=function(i,l){var k;if((i.ownerDocument||i)!==M)Y(i);J||(l=l.toLowerCase());if(k=D.attrHandle[l])return k(i);if(J||F.attributes)return i.getAttribute(l);return((k=i.getAttributeNode(l))||i.getAttribute(l))&&i[l]===true?l:k&&k.specified?
k.value:null};h.error=function(i){throw Error("Syntax error, unrecognized expression: "+i);};h.uniqueSort=function(i){var l,k=[],o=1,q=0;fa=!F.detectDuplicates;i.sort(ua);if(fa){for(;l=i[o];o++)if(l===i[o-1])q=k.push(o);for(;q--;)i.splice(k[q],1)}return i};G=h.getText=function(i){var l,k="",o=0;if(l=i.nodeType)if(l===1||l===9||l===11)if(typeof i.textContent==="string")return i.textContent;else for(i=i.firstChild;i;i=i.nextSibling)k+=G(i);else{if(l===3||l===4)return i.nodeValue}else for(;l=i[o];o++)k+=
G(l);return k};D=h.selectors={cacheLength:50,createPseudo:f,match:Ta,find:{},relative:{">":{dir:"parentNode",first:true}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:true},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(i){i[1]=i[1].replace(ma,na);i[3]=(i[4]||i[5]||"").replace(ma,na);if(i[2]==="~=")i[3]=" "+i[3]+" ";return i.slice(0,4)},CHILD:function(i){i[1]=i[1].toLowerCase();if(i[1].slice(0,3)==="nth"){i[3]||h.error(i[0]);i[4]=+(i[4]?i[5]+(i[6]||1):2*(i[3]==="even"||i[3]==="odd"));
i[5]=+(i[7]+i[8]||i[3]==="odd")}else i[3]&&h.error(i[0]);return i},PSEUDO:function(i){var l,k=!i[5]&&i[2];if(Ta.CHILD.test(i[0]))return null;if(i[4])i[2]=i[4];else if(k&&cd.test(k)&&(l=n(k,true))&&(l=k.indexOf(")",k.length-l)-k.length)){i[0]=i[0].slice(0,l);i[2]=k.slice(0,l)}return i.slice(0,3)}},filter:{TAG:function(i){if(i==="*")return function(){return true};i=i.replace(ma,na).toLowerCase();return function(l){return l.nodeName&&l.nodeName.toLowerCase()===i}},CLASS:function(i){var l=ec[i+" "];return l||
(l=RegExp("(^|[\\x20\\t\\r\\n\\f])"+i+"([\\x20\\t\\r\\n\\f]|$)"))&&ec(i,function(k){return l.test(k.className||typeof k.getAttribute!==la&&k.getAttribute("class")||"")})},ATTR:function(i,l,k){return function(o){o=h.attr(o,i);if(o==null)return l==="!=";if(!l)return true;o+="";return l==="="?o===k:l==="!="?o!==k:l==="^="?k&&o.indexOf(k)===0:l==="*="?k&&o.indexOf(k)>-1:l==="$="?k&&o.substr(o.length-k.length)===k:l==="~="?(" "+o+" ").indexOf(k)>-1:l==="|="?o===k||o.substr(0,k.length+1)===k+"-":false}},
CHILD:function(i,l,k,o,q){var u=i.slice(0,3)!=="nth",s=i.slice(-4)!=="last",w=l==="of-type";return o===1&&q===0?function(x){return!!x.parentNode}:function(x,K,z){var I,E,Q,$,N;K=u!==s?"nextSibling":"previousSibling";var L=x.parentNode,ia=w&&x.nodeName.toLowerCase();z=!z&&!w;if(L){if(u){for(;K;){for(E=x;E=E[K];)if(w?E.nodeName.toLowerCase()===ia:E.nodeType===1)return false;N=K=i==="only"&&!N&&"nextSibling"}return true}N=[s?L.firstChild:L.lastChild];if(s&&z){z=L[H]||(L[H]={});I=z[i]||[];$=I[0]===ca&&
I[1];Q=I[0]===ca&&I[2];for(E=$&&L.childNodes[$];E=++$&&E&&E[K]||(Q=$=0)||N.pop();)if(E.nodeType===1&&++Q&&E===x){z[i]=[ca,$,Q];break}}else if(z&&(I=(x[H]||(x[H]={}))[i])&&I[0]===ca)Q=I[1];else for(;E=++$&&E&&E[K]||(Q=$=0)||N.pop();)if((w?E.nodeName.toLowerCase()===ia:E.nodeType===1)&&++Q){if(z)(E[H]||(E[H]={}))[i]=[ca,Q];if(E===x)break}Q-=q;return Q===o||Q%o===0&&Q/o>=0}}},PSEUDO:function(i,l){var k,o=D.pseudos[i]||D.setFilters[i.toLowerCase()]||h.error("unsupported pseudo: "+i);if(o[H])return o(l);
if(o.length>1){k=[i,i,"",l];return D.setFilters.hasOwnProperty(i.toLowerCase())?f(function(q,u){for(var s,w=o(q,l),x=w.length;x--;){s=mb.call(q,w[x]);q[s]=!(u[s]=w[x])}}):function(q){return o(q,0,k)}}return o}},pseudos:{not:f(function(i){var l=[],k=[],o=P(i.replace(Sa,"$1"));return o[H]?f(function(q,u,s,w){w=o(q,null,w,[]);for(var x=q.length;x--;)if(s=w[x])q[x]=!(u[x]=s)}):function(q,u,s){l[0]=q;o(l,null,s,k);return!k.pop()}}),has:f(function(i){return function(l){return h(i,l).length>0}}),contains:f(function(i){return function(l){return(l.textContent||
l.innerText||G(l)).indexOf(i)>-1}}),lang:f(function(i){dd.test(i||"")||h.error("unsupported lang: "+i);i=i.replace(ma,na).toLowerCase();return function(l){var k;do if(k=J?l.getAttribute("xml:lang")||l.getAttribute("lang"):l.lang){k=k.toLowerCase();return k===i||k.indexOf(i+"-")===0}while((l=l.parentNode)&&l.nodeType===1);return false}}),target:function(i){var l=a.location&&a.location.hash;return l&&l.slice(1)===i.id},root:function(i){return i===R},focus:function(i){return i===M.activeElement&&(!M.hasFocus||
M.hasFocus())&&!!(i.type||i.href||~i.tabIndex)},enabled:function(i){return i.disabled===false},disabled:function(i){return i.disabled===true},checked:function(i){var l=i.nodeName.toLowerCase();return l==="input"&&!!i.checked||l==="option"&&!!i.selected},selected:function(i){return i.selected===true},empty:function(i){for(i=i.firstChild;i;i=i.nextSibling)if(i.nodeName>"@"||i.nodeType===3||i.nodeType===4)return false;return true},parent:function(i){return!D.pseudos.empty(i)},header:function(i){return fd.test(i.nodeName)},
input:function(i){return ed.test(i.nodeName)},button:function(i){var l=i.nodeName.toLowerCase();return l==="input"&&i.type==="button"||l==="button"},text:function(i){var l;return i.nodeName.toLowerCase()==="input"&&i.type==="text"&&((l=i.getAttribute("type"))==null||l.toLowerCase()===i.type)},first:r(function(){return[0]}),last:r(function(i,l){return[l-1]}),eq:r(function(i,l,k){return[k<0?k+l:k]}),even:r(function(i,l){for(var k=0;k<l;k+=2)i.push(k);return i}),odd:r(function(i,l){for(var k=1;k<l;k+=
2)i.push(k);return i}),lt:r(function(i,l,k){for(l=k<0?k+l:k;--l>=0;)i.push(l);return i}),gt:r(function(i,l,k){for(k=k<0?k+l:k;++k<l;)i.push(k);return i})}};for(ka in{radio:true,checkbox:true,file:true,password:true,image:true})D.pseudos[ka]=m(ka);for(ka in{submit:true,reset:true})D.pseudos[ka]=p(ka);P=h.compile=function(i,l){var k,o=[],q=[],u=fc[i+" "];if(!u){l||(l=n(i));for(k=l.length;k--;){u=Fa(l[k]);u[H]?o.push(u):q.push(u)}u=fc(i,Ua(q,o))}return u};D.pseudos.nth=D.pseudos.eq;D.filters=da.prototype=
D.pseudos;D.setFilters=new da;Y();h.attr=c.attr;c.find=h;c.expr=h.selectors;c.expr[":"]=c.expr.pseudos;c.unique=h.uniqueSort;c.text=h.getText;c.isXMLDoc=h.isXML;c.contains=h.contains})(C);var hd=/Until$/,id=/^(?:parents|prev(?:Until|All))/,zc=/^.[^:#\[\.,]*$/,hc=c.expr.match.needsContext,jd={children:true,contents:true,next:true,prev:true};c.fn.extend({find:function(a){var b,d,e;if(typeof a!=="string"){e=this;return this.pushStack(c(a).filter(function(){for(b=0;b<e.length;b++)if(c.contains(e[b],this))return true}))}d=
[];for(b=0;b<this.length;b++)c.find(a,this[b],d);d=this.pushStack(c.unique(d));d.selector=(this.selector?this.selector+" ":"")+a;return d},has:function(a){var b,d=c(a,this),e=d.length;return this.filter(function(){for(b=0;b<e;b++)if(c.contains(this,d[b]))return true})},not:function(a){return this.pushStack(Ab(this,a,false))},filter:function(a){return this.pushStack(Ab(this,a,true))},is:function(a){return!!a&&(typeof a==="string"?hc.test(a)?c(a,this.context).index(this[0])>=0:c.filter(a,this).length>
0:this.filter(a).length>0)},closest:function(a,b){for(var d,e=0,f=this.length,g=[],h=hc.test(a)||typeof a!=="string"?c(a,b||this.context):0;e<f;e++)for(d=this[e];d&&d.ownerDocument&&d!==b&&d.nodeType!==11;){if(h?h.index(d)>-1:c.find.matchesSelector(d,a)){g.push(d);break}d=d.parentNode}return this.pushStack(g.length>1?c.unique(g):g)},index:function(a){if(!a)return this[0]&&this[0].parentNode?this.first().prevAll().length:-1;if(typeof a==="string")return c.inArray(this[0],c(a));return c.inArray(a.jquery?
a[0]:a,this)},add:function(a,b){var d=typeof a==="string"?c(a,b):c.makeArray(a&&a.nodeType?[a]:a);d=c.merge(this.get(),d);return this.pushStack(c.unique(d))},addBack:function(a){return this.add(a==null?this.prevObject:this.prevObject.filter(a))}});c.fn.andSelf=c.fn.addBack;c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return zb(a,"nextSibling")},
prev:function(a){return zb(a,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling((a.parentNode||{}).firstChild,a)},children:function(a){return c.sibling(a.firstChild)},contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.merge([],
a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);hd.test(a)||(e=d);if(e&&typeof e==="string")f=c.filter(e,f);f=this.length>1&&!jd[a]?c.unique(f):f;if(this.length>1&&id.test(a))f=f.reverse();return this.pushStack(f)}});c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return b.length===1?c.find.matchesSelector(b[0],a)?[b[0]]:[]:c.find.matches(a,b)},dir:function(a,b,d){var e=[];for(a=a[b];a&&a.nodeType!==9&&(d===t||a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&e.push(a);
a=a[b]}return e},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var Cb="abbr|article|aside|audio|bdi|canvas|data|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",kd=/ jQuery\d+="(?:null|\d+)"/g,ic=RegExp("<(?:"+Cb+")[\\s/>]","i"),ob=/^\s+/,jc=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,kc=/<([\w:]+)/,lc=/<tbody/i,ld=/<|&#?\w+;/,md=/<(?:script|style|link)/i,
Za=/^(?:checkbox|radio)$/i,nd=/checked\s*(?:[^=]|=\s*.checked.)/i,mc=/^$|\/(?:java|ecma)script/i,Ac=/^true\/(.*)/,od=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g,ea={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],area:[1,"<map>","</map>"],param:[1,"<object>","</object>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],
_default:c.support.htmlSerialize?[0,"",""]:[1,"X<div>","</div>"]},pb=Bb(A).appendChild(A.createElement("div"));ea.optgroup=ea.option;ea.tbody=ea.tfoot=ea.colgroup=ea.caption=ea.thead;ea.th=ea.td;c.fn.extend({text:function(a){return c.access(this,function(b){return b===t?c.text(this):this.empty().append((this[0]&&this[0].ownerDocument||A).createTextNode(b))},null,a,arguments.length)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,d))});if(this[0]){var b=
c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var d=this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){var b=c.isFunction(a);return this.each(function(d){c(this).wrapAll(b?a.call(this,
d):a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,true,function(a){if(this.nodeType===1||this.nodeType===11||this.nodeType===9)this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){if(this.nodeType===1||this.nodeType===11||this.nodeType===9)this.insertBefore(a,this.firstChild)})},before:function(){return this.domManip(arguments,false,
function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return this.domManip(arguments,false,function(a){this.parentNode&&this.parentNode.insertBefore(a,this.nextSibling)})},remove:function(a,b){for(var d,e=0;(d=this[e])!=null;e++)if(!a||c.filter(a,[d]).length>0){!b&&d.nodeType===1&&c.cleanData(aa(d));if(d.parentNode){b&&c.contains(d.ownerDocument,d)&&Ya(aa(d,"script"));d.parentNode.removeChild(d)}}return this},empty:function(){for(var a,b=0;(a=this[b])!=null;b++){for(a.nodeType===
1&&c.cleanData(aa(a,false));a.firstChild;)a.removeChild(a.firstChild);if(a.options&&c.nodeName(a,"select"))a.options.length=0}return this},clone:function(a,b){a=a==null?false:a;b=b==null?a:b;return this.map(function(){return c.clone(this,a,b)})},html:function(a){return c.access(this,function(b){var d=this[0]||{},e=0,f=this.length;if(b===t)return d.nodeType===1?d.innerHTML.replace(kd,""):t;if(typeof b==="string"&&!md.test(b)&&(c.support.htmlSerialize||!ic.test(b))&&(c.support.leadingWhitespace||!ob.test(b))&&
!ea[(kc.exec(b)||["",""])[1].toLowerCase()]){b=b.replace(jc,"<$1></$2>");try{for(;e<f;e++){d=this[e]||{};if(d.nodeType===1){c.cleanData(aa(d,false));d.innerHTML=b}}d=0}catch(g){}}d&&this.empty().append(b)},null,a,arguments.length)},replaceWith:function(a){if(!c.isFunction(a)&&typeof a!=="string")a=c(a).not(this).detach();return this.domManip([a],true,function(b){var d=this.nextSibling,e=this.parentNode;if(e&&this.nodeType===1||this.nodeType===11){c(this).remove();d?d.parentNode.insertBefore(b,d):
e.appendChild(b)}})},detach:function(a){return this.remove(a,true)},domManip:function(a,b,d){a=Wb.apply([],a);var e,f,g,h,j=0,m=this.length,p=this,r=m-1,n=a[0],v=c.isFunction(n);if(v||!(m<=1||typeof n!=="string"||c.support.checkClone||!nd.test(n)))return this.each(function(y){var O=p.eq(y);if(v)a[0]=n.call(this,y,b?O.html():t);O.domManip(a,b,d)});if(m){e=c.buildFragment(a,this[0].ownerDocument,false,this);f=e.firstChild;if(e.childNodes.length===1)e=f;if(f){b=b&&c.nodeName(f,"tr");f=c.map(aa(e,"script"),
Db);for(g=f.length;j<m;j++){h=e;if(j!==r){h=c.clone(h,true,true);g&&c.merge(f,aa(h,"script"))}d.call(b&&c.nodeName(this[j],"table")?this[j].getElementsByTagName("tbody")[0]||this[j].appendChild(this[j].ownerDocument.createElement("tbody")):this[j],h,j)}if(g){e=f[f.length-1].ownerDocument;c.map(f,Eb);for(j=0;j<g;j++){h=f[j];if(mc.test(h.type||"")&&!c._data(h,"globalEval")&&c.contains(e,h))h.src?c.ajax({url:h.src,type:"GET",dataType:"script",async:false,global:false,"throws":true}):c.globalEval((h.text||
h.textContent||h.innerHTML||"").replace(od,""))}}e=f=null}}return this}});c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(d){for(var e=0,f=[],g=c(d),h=g.length-1;e<=h;e++){d=e===h?this:this.clone(true);c(g[e])[b](d);cb.apply(f,d.get())}return this.pushStack(f)}});c.extend({clone:function(a,b,d){var e,f,g,h,j,m=c.contains(a.ownerDocument,a);if(c.support.html5Clone||c.isXMLDoc(a)||!ic.test("<"+a.nodeName+
">"))j=a.cloneNode(true);else{pb.innerHTML=a.outerHTML;pb.removeChild(j=pb.firstChild)}if((!c.support.noCloneEvent||!c.support.noCloneChecked)&&(a.nodeType===1||a.nodeType===11)&&!c.isXMLDoc(a)){e=aa(j);f=aa(a);for(h=0;(g=f[h])!=null;++h)if(e[h]){g=g;var p=e[h],r=void 0,n=void 0,v=void 0;if(p.nodeType===1){r=p.nodeName.toLowerCase();if(!c.support.noCloneEvent&&p[c.expando]){n=c._data(p);for(v in n.events)c.removeEvent(p,v,n.handle);p.removeAttribute(c.expando)}if(r==="script"&&p.text!==g.text){Db(p).text=
g.text;Eb(p)}else if(r==="object"){if(p.parentNode)p.outerHTML=g.outerHTML;if(c.support.html5Clone&&g.innerHTML&&!c.trim(p.innerHTML))p.innerHTML=g.innerHTML}else if(r==="input"&&Za.test(g.type)){p.defaultChecked=p.checked=g.checked;if(p.value!==g.value)p.value=g.value}else if(r==="option")p.defaultSelected=p.selected=g.defaultSelected;else if(r==="input"||r==="textarea")p.defaultValue=g.defaultValue}}}if(b)if(d){f=f||aa(a);e=e||aa(j);for(h=0;(g=f[h])!=null;h++)Fb(g,e[h])}else Fb(a,j);e=aa(j,"script");
e.length>0&&Ya(e,!m&&aa(a,"script"));return j},buildFragment:function(a,b,d,e){for(var f,g,h,j,m,p,r=a.length,n=Bb(b),v=[],y=0;y<r;y++)if((f=a[y])||f===0)if(c.type(f)==="object")c.merge(v,f.nodeType?[f]:f);else if(ld.test(f)){h=h||n.appendChild(b.createElement("div"));g=(kc.exec(f)||["",""])[1].toLowerCase();j=ea[g]||ea._default;h.innerHTML=j[1]+f.replace(jc,"<$1></$2>")+j[2];for(p=j[0];p--;)h=h.lastChild;!c.support.leadingWhitespace&&ob.test(f)&&v.push(b.createTextNode(ob.exec(f)[0]));if(!c.support.tbody)for(p=
(f=g==="table"&&!lc.test(f)?h.firstChild:j[1]==="<table>"&&!lc.test(f)?h:0)&&f.childNodes.length;p--;)if(c.nodeName(m=f.childNodes[p],"tbody")&&!m.childNodes.length)f.removeChild(m);c.merge(v,h.childNodes);for(h.textContent="";h.firstChild;)h.removeChild(h.firstChild);h=n.lastChild}else v.push(b.createTextNode(f));h&&n.removeChild(h);c.support.appendChecked||c.grep(aa(v,"input"),Bc);for(y=0;f=v[y++];)if(!(e&&c.inArray(f,e)!==-1)){a=c.contains(f.ownerDocument,f);h=aa(n.appendChild(f),"script");a&&
Ya(h);if(d)for(p=0;f=h[p++];)if(mc.test(f.type||""))d.push(f)}return n},cleanData:function(a,b){for(var d,e,f,g,h=0,j=c.expando,m=c.cache,p=c.support.deleteExpando,r=c.event.special;(f=a[h])!=null;h++)if(b||c.acceptData(f))if(d=(e=f[j])&&m[e]){if(d.events)for(g in d.events)r[g]?c.event.remove(f,g):c.removeEvent(f,g,d.handle);if(m[e]){delete m[e];if(p)delete f[j];else if(typeof f.removeAttribute!=="undefined")f.removeAttribute(j);else f[j]=null;xa.push(e)}}}});var ra,qa,Ia,qb=/alpha\([^)]*\)/i,pd=
/opacity\s*=\s*([^)]*)/,qd=/^(top|right|bottom|left)$/,rd=/^(none|table(?!-c[ea]).+)/,nc=/^margin/,Cc=RegExp("^("+Qa+")(.*)$","i"),La=RegExp("^("+Qa+")(?!px)[a-z%]+$","i"),sd=RegExp("^([+-])=("+Qa+")","i"),Nb={BODY:"block"},td={position:"absolute",visibility:"hidden",display:"block"},oc={letterSpacing:0,fontWeight:400},pa=["Top","Right","Bottom","Left"],Hb=["Webkit","O","Moz","ms"];c.fn.extend({css:function(a,b){return c.access(this,function(d,e,f){var g,h={},j=0;if(c.isArray(e)){f=qa(d);for(g=e.length;j<
g;j++)h[e[j]]=c.css(d,e[j],false,f);return h}return f!==t?c.style(d,e,f):c.css(d,e)},a,b,arguments.length>1)},show:function(){return Ib(this,true)},hide:function(){return Ib(this)},toggle:function(a){var b=typeof a==="boolean";return this.each(function(){(b?a:Ha(this))?c(this).show():c(this).hide()})}});c.extend({cssHooks:{opacity:{get:function(a,b){if(b){var d=ra(a,"opacity");return d===""?"1":d}}}},cssNumber:{columnCount:true,fillOpacity:true,fontWeight:true,lineHeight:true,opacity:true,orphans:true,
widows:true,zIndex:true,zoom:true},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,b,d,e){if(!(!a||a.nodeType===3||a.nodeType===8||!a.style)){var f,g,h,j=c.camelCase(b),m=a.style;b=c.cssProps[j]||(c.cssProps[j]=Gb(m,j));h=c.cssHooks[b]||c.cssHooks[j];if(d!==t){g=typeof d;if(g==="string"&&(f=sd.exec(d))){d=(f[1]+1)*f[2]+parseFloat(c.css(a,b));g="number"}if(!(d==null||g==="number"&&isNaN(d))){if(g==="number"&&!c.cssNumber[j])d+="px";if(!c.support.clearCloneStyle&&d===
""&&b.indexOf("background")===0)m[b]="inherit";if(!h||!("set"in h)||(d=h.set(a,d,e))!==t)try{m[b]=d}catch(p){}}}else{if(h&&"get"in h&&(f=h.get(a,false,e))!==t)return f;return m[b]}}},css:function(a,b,d,e){var f,g;g=c.camelCase(b);b=c.cssProps[g]||(c.cssProps[g]=Gb(a.style,g));if((g=c.cssHooks[b]||c.cssHooks[g])&&"get"in g)f=g.get(a,true,d);if(f===t)f=ra(a,b,e);if(f==="normal"&&b in oc)f=oc[b];if(d){a=parseFloat(f);return d===true||c.isNumeric(a)?a||0:f}return f},swap:function(a,b,d,e){var f,g={};
for(f in b){g[f]=a.style[f];a.style[f]=b[f]}d=d.apply(a,e||[]);for(f in b)a.style[f]=g[f];return d}});if(C.getComputedStyle){qa=function(a){return C.getComputedStyle(a,null)};ra=function(a,b,d){var e;var f=(d=d||qa(a))?d.getPropertyValue(b)||d[b]:t,g=a.style;if(d){if(f===""&&!c.contains(a.ownerDocument,a))f=c.style(a,b);if(La.test(f)&&nc.test(b)){a=g.width;b=g.minWidth;e=g.maxWidth;g.minWidth=g.maxWidth=g.width=f;f=d.width;g.width=a;g.minWidth=b;g.maxWidth=e}}return f}}else if(A.documentElement.currentStyle){qa=
function(a){return a.currentStyle};ra=function(a,b,d){var e,f,g=(d=d||qa(a))?d[b]:t,h=a.style;if(g==null&&h&&h[b])g=h[b];if(La.test(g)&&!qd.test(b)){d=h.left;if(f=(e=a.runtimeStyle)&&e.left)e.left=a.currentStyle.left;h.left=b==="fontSize"?"1em":g;g=h.pixelLeft+"px";h.left=d;if(f)e.left=f}return g===""?"auto":g}}c.each(["height","width"],function(a,b){c.cssHooks[b]={get:function(d,e,f){if(e)return d.offsetWidth===0&&rd.test(c.css(d,"display"))?c.swap(d,td,function(){return Mb(d,b,f)}):Mb(d,b,f)},set:function(d,
e,f){var g=f&&qa(d);return Kb(d,e,f?Lb(d,b,f,c.support.boxSizing&&c.css(d,"boxSizing",false,g)==="border-box",g):0)}}});if(!c.support.opacity)c.cssHooks.opacity={get:function(a,b){return pd.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?0.01*parseFloat(RegExp.$1)+"":b?"1":""},set:function(a,b){var d=a.style,e=a.currentStyle,f=c.isNumeric(b)?"alpha(opacity="+b*100+")":"",g=e&&e.filter||d.filter||"";d.zoom=1;if((b>=1||b==="")&&c.trim(g.replace(qb,""))===""&&d.removeAttribute){d.removeAttribute("filter");
if(b===""||e&&!e.filter)return}d.filter=qb.test(g)?g.replace(qb,f):g+" "+f}};c(function(){if(!c.support.reliableMarginRight)c.cssHooks.marginRight={get:function(a,b){if(b)return c.swap(a,{display:"inline-block"},ra,[a,"marginRight"])}};!c.support.pixelPosition&&c.fn.position&&c.each(["top","left"],function(a,b){c.cssHooks[b]={get:function(d,e){if(e){e=ra(d,b);return La.test(e)?c(d).position()[b]+"px":e}}}})});if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){return a.offsetWidth===0&&a.offsetHeight===
0||!c.support.reliableHiddenOffsets&&(a.style&&a.style.display||c.css(a,"display"))==="none"};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}c.each({margin:"",padding:"",border:"Width"},function(a,b){c.cssHooks[a+b]={expand:function(d){var e=0,f={};for(d=typeof d==="string"?d.split(" "):[d];e<4;e++)f[a+pa[e]+b]=d[e]||d[e-2]||d[0];return f}};if(!nc.test(a))c.cssHooks[a+b].set=Kb});var Dc=/\[\]$/,pc=/\r?\n/g,ud=/^(?:submit|button|image|reset)$/i,vd=/^(?:input|select|textarea|keygen)/i;
c.fn.extend({serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=c.prop(this,"elements");return a?c.makeArray(a):this}).filter(function(){var a=this.type;return this.name&&!c(this).is(":disabled")&&vd.test(this.nodeName)&&!ud.test(a)&&(this.checked||!Za.test(a))}).map(function(a,b){var d=c(this).val();return d==null?null:c.isArray(d)?c.map(d,function(e){return{name:b.name,value:e.replace(pc,"\r\n")}}):{name:b.name,value:d.replace(pc,
"\r\n")}}).get()}});c.param=function(a,b){var d,e=[],f=function(g,h){h=c.isFunction(h)?h():h==null?"":h;e[e.length]=encodeURIComponent(g)+"="+encodeURIComponent(h)};if(b===t)b=c.ajaxSettings&&c.ajaxSettings.traditional;if(c.isArray(a)||a.jquery&&!c.isPlainObject(a))c.each(a,function(){f(this.name,this.value)});else for(d in a)$a(d,a[d],b,f);return e.join("&")};var wa,oa,rb=c.now(),sb=/\?/,wd=/#.*$/,qc=/([?&])_=[^&]*/,xd=/^(.*?):[ \t]*([^\r\n]*)\r?$/mg,yd=/^(?:GET|HEAD)$/,zd=/^\/\//,rc=/^([\w.+-]+:)(?:\/\/([^\/?#:]*)(?::(\d+)|)|)/,
sc=c.fn.load,tc={},ab={},uc="*/".concat("*");try{oa=Aa.href}catch(Fd){oa=A.createElement("a");oa.href="";oa=oa.href}wa=rc.exec(oa.toLowerCase())||[];c.fn.load=function(a,b,d){if(typeof a!=="string"&&sc)return sc.apply(this,arguments);var e,f,g,h=this,j=a.indexOf(" ");if(j>=0){e=a.slice(j,a.length);a=a.slice(0,j)}if(c.isFunction(b)){d=b;b=t}else if(b&&typeof b==="object")f="POST";h.length>0&&c.ajax({url:a,type:f,dataType:"html",data:b}).done(function(m){g=arguments;h.html(e?c("<div>").append(c.parseHTML(m)).find(e):
m)}).complete(d&&function(m,p){h.each(d,g||[m.responseText,p,m])});return this};c.each(["ajaxStart","ajaxStop","ajaxComplete","ajaxError","ajaxSuccess","ajaxSend"],function(a,b){c.fn[b]=function(d){return this.on(b,d)}});c.each(["get","post"],function(a,b){c[b]=function(d,e,f,g){if(c.isFunction(e)){g=g||f;f=e;e=t}return c.ajax({url:d,type:b,dataType:g,data:e,success:f})}});c.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:oa,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(wa[1]),
global:true,processData:true,async:true,contentType:"application/x-www-form-urlencoded; charset=UTF-8",accepts:{"*":uc,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",text:"responseText"},converters:{"* text":C.String,"text html":true,"text json":c.parseJSON,"text xml":c.parseXML},flatOptions:{url:true,context:true}},ajaxSetup:function(a,b){return b?bb(bb(a,c.ajaxSettings),
b):bb(c.ajaxSettings,a)},ajaxPrefilter:Pb(tc),ajaxTransport:Pb(ab),ajax:function(a,b){function d(G,W,P,fa){var T,Y,M,R,J=W;if(da!==2){da=2;j&&clearTimeout(j);e=t;g=fa||"";B.readyState=G>0?4:0;if(P){R=n;fa=B;var Z,S,U,ha,ua=R.contents,H=R.dataTypes,ga=R.responseFields;for(S in ga)if(S in P)fa[ga[S]]=P[S];for(;H[0]==="*";){H.shift();if(Z===t)Z=R.mimeType||fa.getResponseHeader("Content-Type")}if(Z)for(S in ua)if(ua[S]&&ua[S].test(Z)){H.unshift(S);break}if(H[0]in P)U=H[0];else{for(S in P){if(!H[0]||R.converters[S+
" "+H[0]]){U=S;break}ha||(ha=S)}U=U||ha}if(U){U!==H[0]&&H.unshift(U);R=P[U]}else R=void 0}if(G>=200&&G<300||G===304){if(n.ifModified){if(P=B.getResponseHeader("Last-Modified"))c.lastModified[f]=P;if(P=B.getResponseHeader("etag"))c.etag[f]=P}if(G===304){T=true;J="notmodified"}else{a:{Y=n;M=R;var F,ca;J={};Z=0;S=Y.dataTypes.slice();U=S[0];if(Y.dataFilter)M=Y.dataFilter(M,Y.dataType);if(S[1])for(F in Y.converters)J[F.toLowerCase()]=Y.converters[F];for(;P=S[++Z];)if(P!=="*"){if(U!=="*"&&U!==P){F=J[U+
" "+P]||J["* "+P];if(!F)for(ca in J){T=ca.split(" ");if(T[1]===P)if(F=J[U+" "+T[0]]||J["* "+T[0]]){if(F===true)F=J[ca];else if(J[ca]!==true){P=T[0];S.splice(Z--,0,P)}break}}if(F!==true)if(F&&Y["throws"])M=F(M);else try{M=F(M)}catch(kb){T={state:"parsererror",error:F?kb:"No conversion from "+U+" to "+P};break a}}U=P}T={state:"success",data:M}}J=T.state;Y=T.data;M=T.error;T=!M}}else{M=J;if(G||!J){J="error";if(G<0)G=0}}B.status=G;B.statusText=(W||J)+"";T?O.resolveWith(v,[Y,J,B]):O.rejectWith(v,[B,J,
M]);B.statusCode(V);V=t;if(p)y.trigger(T?"ajaxSuccess":"ajaxError",[B,n,T?Y:M]);X.fireWith(v,[B,J]);if(p){y.trigger("ajaxComplete",[B,n]);--c.active||c.event.trigger("ajaxStop")}}}if(typeof a==="object"){b=a;a=t}b=b||{};var e,f,g,h,j,m,p,r,n=c.ajaxSetup({},b),v=n.context||n,y=n.context&&(v.nodeType||v.jquery)?c(v):c.event,O=c.Deferred(),X=c.Callbacks("once memory"),V=n.statusCode||{},Fa={},Ua={},da=0,ka="canceled",B={readyState:0,getResponseHeader:function(G){var W;if(da===2){if(!h)for(h={};W=xd.exec(g);)h[W[1].toLowerCase()]=
W[2];W=h[G.toLowerCase()]}return W==null?null:W},getAllResponseHeaders:function(){return da===2?g:null},setRequestHeader:function(G,W){var P=G.toLowerCase();if(!da){G=Ua[P]=Ua[P]||G;Fa[G]=W}return this},overrideMimeType:function(G){if(!da)n.mimeType=G;return this},statusCode:function(G){var W;if(G)if(da<2)for(W in G)V[W]=[V[W],G[W]];else B.always(G[B.status]);return this},abort:function(G){G=G||ka;e&&e.abort(G);d(0,G);return this}};O.promise(B).complete=X.add;B.success=B.done;B.error=B.fail;n.url=
((a||n.url||oa)+"").replace(wd,"").replace(zd,wa[1]+"//");n.type=b.method||b.type||n.method||n.type;n.dataTypes=c.trim(n.dataType||"*").toLowerCase().match(ja)||[""];if(n.crossDomain==null){m=rc.exec(n.url.toLowerCase());n.crossDomain=!!(m&&(m[1]!==wa[1]||m[2]!==wa[2]||(m[3]||(m[1]==="http:"?80:443))!=(wa[3]||(wa[1]==="http:"?80:443))))}if(n.data&&n.processData&&typeof n.data!=="string")n.data=c.param(n.data,n.traditional);Qb(tc,n,b,B);if(da===2)return B;(p=n.global)&&c.active++===0&&c.event.trigger("ajaxStart");
n.type=n.type.toUpperCase();n.hasContent=!yd.test(n.type);f=n.url;if(!n.hasContent){if(n.data){f=n.url+=(sb.test(f)?"&":"?")+n.data;delete n.data}if(n.cache===false)n.url=qc.test(f)?f.replace(qc,"$1_="+rb++):f+(sb.test(f)?"&":"?")+"_="+rb++}if(n.ifModified){c.lastModified[f]&&B.setRequestHeader("If-Modified-Since",c.lastModified[f]);c.etag[f]&&B.setRequestHeader("If-None-Match",c.etag[f])}if(n.data&&n.hasContent&&n.contentType!==false||b.contentType)B.setRequestHeader("Content-Type",n.contentType);
B.setRequestHeader("Accept",n.dataTypes[0]&&n.accepts[n.dataTypes[0]]?n.accepts[n.dataTypes[0]]+(n.dataTypes[0]!=="*"?", "+uc+"; q=0.01":""):n.accepts["*"]);for(r in n.headers)B.setRequestHeader(r,n.headers[r]);if(n.beforeSend&&(n.beforeSend.call(v,B,n)===false||da===2))return B.abort();ka="abort";for(r in{success:1,error:1,complete:1})B[r](n[r]);if(e=Qb(ab,n,b,B)){B.readyState=1;p&&y.trigger("ajaxSend",[B,n]);if(n.async&&n.timeout>0)j=setTimeout(function(){B.abort("timeout")},n.timeout);try{da=1;
e.send(Fa,d)}catch(D){if(da<2)d(-1,D);else throw D;}}else d(-1,"No Transport");return B},getScript:function(a,b){return c.get(a,t,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")}});c.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/(?:java|ecma)script/},converters:{"text script":function(a){c.globalEval(a);return a}}});c.ajaxPrefilter("script",function(a){if(a.cache===t)a.cache=false;if(a.crossDomain){a.type=
"GET";a.global=false}});c.ajaxTransport("script",function(a){if(a.crossDomain){var b,d=A.head||c("head")[0]||A.documentElement;return{send:function(e,f){b=A.createElement("script");b.async=true;if(a.scriptCharset)b.charset=a.scriptCharset;b.src=a.url;b.onload=b.onreadystatechange=function(g,h){if(h||!b.readyState||/loaded|complete/.test(b.readyState)){b.onload=b.onreadystatechange=null;b.parentNode&&b.parentNode.removeChild(b);b=null;h||f(200,"success")}};d.insertBefore(b,d.firstChild)},abort:function(){b&&
b.onload(t,true)}}}});var vc=[],tb=/(=)\?(?=&|$)|\?\?/;c.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=vc.pop()||c.expando+"_"+rb++;this[a]=true;return a}});c.ajaxPrefilter("json jsonp",function(a,b,d){var e,f,g,h=a.jsonp!==false&&(tb.test(a.url)?"url":typeof a.data==="string"&&!(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&tb.test(a.data)&&"data");if(h||a.dataTypes[0]==="jsonp"){e=a.jsonpCallback=c.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback;if(h)a[h]=
a[h].replace(tb,"$1"+e);else if(a.jsonp!==false)a.url+=(sb.test(a.url)?"&":"?")+a.jsonp+"="+e;a.converters["script json"]=function(){g||c.error(e+" was not called");return g[0]};a.dataTypes[0]="json";f=C[e];C[e]=function(){g=arguments};d.always(function(){C[e]=f;if(a[e]){a.jsonpCallback=b.jsonpCallback;vc.push(e)}g&&c.isFunction(f)&&f(g[0]);g=f=t});return"script"}});var Ga,Ad=0,ub=C.ActiveXObject&&function(){for(var a in Ga)Ga[a](t,true)};c.ajaxSettings.xhr=C.ActiveXObject?function(){var a;if(!(a=
!this.isLocal&&Rb()))a:{try{a=new C.ActiveXObject("Microsoft.XMLHTTP");break a}catch(b){}a=void 0}return a}:Rb;Aa=c.ajaxSettings.xhr();c.support.cors=!!Aa&&"withCredentials"in Aa;(Aa=c.support.ajax=!!Aa)&&c.ajaxTransport(function(a){if(!a.crossDomain||c.support.cors){var b;return{send:function(d,e){var f,g,h=a.xhr();a.username?h.open(a.type,a.url,a.async,a.username,a.password):h.open(a.type,a.url,a.async);if(a.xhrFields)for(g in a.xhrFields)h[g]=a.xhrFields[g];a.mimeType&&h.overrideMimeType&&h.overrideMimeType(a.mimeType);
if(!a.crossDomain&&!d["X-Requested-With"])d["X-Requested-With"]="XMLHttpRequest";try{for(g in d)h.setRequestHeader(g,d[g])}catch(j){}h.send(a.hasContent&&a.data||null);b=function(m,p){var r,n,v,y,O;try{if(b&&(p||h.readyState===4)){b=t;if(f){h.onreadystatechange=c.noop;ub&&delete Ga[f]}if(p)h.readyState!==4&&h.abort();else{y={};r=h.status;O=h.responseXML;v=h.getAllResponseHeaders();if(O&&O.documentElement)y.xml=O;if(typeof h.responseText==="string")y.text=h.responseText;try{n=h.statusText}catch(X){n=
""}if(!r&&a.isLocal&&!a.crossDomain)r=y.text?200:404;else if(r===1223)r=204}}}catch(V){p||e(-1,V)}y&&e(r,n,y,v)};if(a.async)if(h.readyState===4)setTimeout(b);else{f=++Ad;if(ub){if(!Ga){Ga={};c(C).unload(ub)}Ga[f]=b}h.onreadystatechange=b}else b()},abort:function(){b&&b(t,true)}}}});var za,Va,Bd=/^(?:toggle|show|hide)$/,Cd=RegExp("^(?:([+-])=|)("+Qa+")([a-z%]*)$","i"),Dd=/queueHooks$/,Ma=[function(a,b,d){var e,f,g,h,j,m,p=this,r=a.style,n={},v=[],y=a.nodeType&&Ha(a);if(!d.queue){j=c._queueHooks(a,
"fx");if(j.unqueued==null){j.unqueued=0;m=j.empty.fire;j.empty.fire=function(){j.unqueued||m()}}j.unqueued++;p.always(function(){p.always(function(){j.unqueued--;c.queue(a,"fx").length||j.empty.fire()})})}if(a.nodeType===1&&("height"in b||"width"in b)){d.overflow=[r.overflow,r.overflowX,r.overflowY];if(c.css(a,"display")==="inline"&&c.css(a,"float")==="none")if(!c.support.inlineBlockNeedsLayout||Jb(a.nodeName)==="inline")r.display="inline-block";else r.zoom=1}if(d.overflow){r.overflow="hidden";c.support.shrinkWrapBlocks||
p.done(function(){r.overflow=d.overflow[0];r.overflowX=d.overflow[1];r.overflowY=d.overflow[2]})}for(e in b){g=b[e];if(Bd.exec(g)){delete b[e];f=f||g==="toggle";if(g!==(y?"hide":"show"))v.push(e)}}if(b=v.length){g=c._data(a,"fxshow")||c._data(a,"fxshow",{});if("hidden"in g)y=g.hidden;if(f)g.hidden=!y;y?c(a).show():p.done(function(){c(a).hide()});p.done(function(){var O;c._removeData(a,"fxshow");for(O in n)c.style(a,O,n[O])});for(e=0;e<b;e++){f=v[e];h=p.createTween(f,y?g[f]:0);n[f]=g[f]||c.style(a,
f);if(!(f in g)){g[f]=h.start;if(y){h.end=h.start;h.start=f==="width"||f==="height"?1:0}}}}}],Ja={"*":[function(a,b){var d,e,f=this.createTween(a,b),g=Cd.exec(b),h=f.cur(),j=+h||0,m=1,p=20;if(g){d=+g[2];e=g[3]||(c.cssNumber[a]?"":"px");if(e!=="px"&&j){j=c.css(f.elem,a,true)||d||1;do{m=m||".5";j/=m;c.style(f.elem,a,j+e)}while(m!==(m=f.cur()/h)&&m!==1&&--p)}f.unit=e;f.start=j;f.end=g[1]?j+(g[1]+1)*d:d}return f}]};c.Animation=c.extend(Tb,{tweener:function(a,b){if(c.isFunction(a)){b=a;a=["*"]}else a=
a.split(" ");for(var d,e=0,f=a.length;e<f;e++){d=a[e];Ja[d]=Ja[d]||[];Ja[d].unshift(b)}},prefilter:function(a,b){b?Ma.unshift(a):Ma.push(a)}});c.Tween=ba;ba.prototype={constructor:ba,init:function(a,b,d,e,f,g){this.elem=a;this.prop=d;this.easing=f||"swing";this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(c.cssNumber[d]?"":"px")},cur:function(){var a=ba.propHooks[this.prop];return a&&a.get?a.get(this):ba.propHooks._default.get(this)},run:function(a){var b,d=ba.propHooks[this.prop];
this.pos=this.options.duration?b=c.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):b=a;this.now=(this.end-this.start)*b+this.start;this.options.step&&this.options.step.call(this.elem,this.now,this);d&&d.set?d.set(this):ba.propHooks._default.set(this);return this}};ba.prototype.init.prototype=ba.prototype;ba.propHooks={_default:{get:function(a){if(a.elem[a.prop]!=null&&(!a.elem.style||a.elem.style[a.prop]==null))return a.elem[a.prop];a=c.css(a.elem,a.prop,"auto");return!a||
a==="auto"?0:a},set:function(a){if(c.fx.step[a.prop])c.fx.step[a.prop](a);else if(a.elem.style&&(a.elem.style[c.cssProps[a.prop]]!=null||c.cssHooks[a.prop]))c.style(a.elem,a.prop,a.now+a.unit);else a.elem[a.prop]=a.now}}};ba.propHooks.scrollTop=ba.propHooks.scrollLeft={set:function(a){if(a.elem.nodeType&&a.elem.parentNode)a.elem[a.prop]=a.now}};c.each(["toggle","show","hide"],function(a,b){var d=c.fn[b];c.fn[b]=function(e,f,g){return e==null||typeof e==="boolean"?d.apply(this,arguments):this.animate(Na(b,
true),e,f,g)}});c.fn.extend({fadeTo:function(a,b,d,e){return this.filter(Ha).css("opacity",0).show().end().animate({opacity:b},a,d,e)},animate:function(a,b,d,e){var f=c.isEmptyObject(a),g=c.speed(b,d,e),h=function(){var j=Tb(this,c.extend({},a),g);h.finish=function(){j.stop(true)};if(f||c._data(this,"finish"))j.stop(true)};h.finish=h;return f||g.queue===false?this.each(h):this.queue(g.queue,h)},stop:function(a,b,d){var e=function(f){var g=f.stop;delete f.stop;g(d)};if(typeof a!=="string"){d=b;b=a;
a=t}if(b&&a!==false)this.queue(a||"fx",[]);return this.each(function(){var f=true,g=a!=null&&a+"queueHooks",h=c.timers,j=c._data(this);if(g)j[g]&&j[g].stop&&e(j[g]);else for(g in j)j[g]&&j[g].stop&&Dd.test(g)&&e(j[g]);for(g=h.length;g--;)if(h[g].elem===this&&(a==null||h[g].queue===a)){h[g].anim.stop(d);f=false;h.splice(g,1)}if(f||!d)c.dequeue(this,a)})},finish:function(a){if(a!==false)a=a||"fx";return this.each(function(){var b,d=c._data(this),e=d[a+"queue"];b=d[a+"queueHooks"];var f=c.timers,g=e?
e.length:0;d.finish=true;c.queue(this,a,[]);b&&b.cur&&b.cur.finish&&b.cur.finish.call(this);for(b=f.length;b--;)if(f[b].elem===this&&f[b].queue===a){f[b].anim.stop(true);f.splice(b,1)}for(b=0;b<g;b++)e[b]&&e[b].finish&&e[b].finish.call(this);delete d.finish})}});c.each({slideDown:Na("show"),slideUp:Na("hide"),slideToggle:Na("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=function(d,e,f){return this.animate(b,d,e,f)}});c.speed=function(a,
b,d){var e=a&&typeof a==="object"?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off?0:typeof e.duration==="number"?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;if(e.queue==null||e.queue===true)e.queue="fx";e.old=e.complete;e.complete=function(){c.isFunction(e.old)&&e.old.call(this);e.queue&&c.dequeue(this,e.queue)};return e};c.easing={linear:function(a){return a},swing:function(a){return 0.5-
Math.cos(a*Math.PI)/2}};c.timers=[];c.fx=ba.prototype.init;c.fx.tick=function(){var a,b=c.timers,d=0;for(za=c.now();d<b.length;d++){a=b[d];!a()&&b[d]===a&&b.splice(d--,1)}b.length||c.fx.stop();za=t};c.fx.timer=function(a){a()&&c.timers.push(a)&&c.fx.start()};c.fx.interval=13;c.fx.start=function(){Va||(Va=setInterval(c.fx.tick,c.fx.interval))};c.fx.stop=function(){clearInterval(Va);Va=null};c.fx.speeds={slow:600,fast:200,_default:400};c.fx.step={};if(c.expr&&c.expr.filters)c.expr.filters.animated=
function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};c.fn.offset=function(a){if(arguments.length)return a===t?this:this.each(function(g){c.offset.setOffset(this,a,g)});var b,d,e={top:0,left:0},f=(d=this[0])&&d.ownerDocument;if(f){b=f.documentElement;if(!c.contains(b,d))return e;if(typeof d.getBoundingClientRect!=="undefined")e=d.getBoundingClientRect();d=Ub(f);return{top:e.top+(d.pageYOffset||b.scrollTop)-(b.clientTop||0),left:e.left+(d.pageXOffset||b.scrollLeft)-(b.clientLeft||
0)}}};c.offset={setOffset:function(a,b,d){var e=c.css(a,"position");if(e==="static")a.style.position="relative";var f=c(a),g=f.offset(),h=c.css(a,"top"),j=c.css(a,"left"),m={},p={};if((e==="absolute"||e==="fixed")&&c.inArray("auto",[h,j])>-1){p=f.position();e=p.top;j=p.left}else{e=parseFloat(h)||0;j=parseFloat(j)||0}if(c.isFunction(b))b=b.call(a,d,g);if(b.top!=null)m.top=b.top-g.top+e;if(b.left!=null)m.left=b.left-g.left+j;"using"in b?b.using.call(a,m):f.css(m)}};c.fn.extend({position:function(){if(this[0]){var a,
b,d={top:0,left:0},e=this[0];if(c.css(e,"position")==="fixed")b=e.getBoundingClientRect();else{a=this.offsetParent();b=this.offset();c.nodeName(a[0],"html")||(d=a.offset());d.top+=c.css(a[0],"borderTopWidth",true);d.left+=c.css(a[0],"borderLeftWidth",true)}return{top:b.top-d.top-c.css(e,"marginTop",true),left:b.left-d.left-c.css(e,"marginLeft",true)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||A.documentElement;a&&!c.nodeName(a,"html")&&c.css(a,"position")===
"static";)a=a.offsetParent;return a||A.documentElement})}});c.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var d=/Y/.test(b);c.fn[a]=function(e){return c.access(this,function(f,g,h){var j=Ub(f);if(h===t)return j?b in j?j[b]:j.document.documentElement[g]:f[g];if(j)j.scrollTo(!d?h:c(j).scrollLeft(),d?h:c(j).scrollTop());else f[g]=h},a,e,arguments.length,null)}});c.each({Height:"height",Width:"width"},function(a,b){c.each({padding:"inner"+a,content:b,"":"outer"+a},function(d,
e){c.fn[e]=function(f,g){var h=arguments.length&&(d||typeof f!=="boolean"),j=d||(f===true||g===true?"margin":"border");return c.access(this,function(m,p,r){if(c.isWindow(m))return m.document.documentElement["client"+a];if(m.nodeType===9){p=m.documentElement;return Math.max(m.body["scroll"+a],p["scroll"+a],m.body["offset"+a],p["offset"+a],p["client"+a])}return r===t?c.css(m,p,j):c.style(m,p,r,j)},b,h?f:t,h,null)}})});C.jQuery=C.$=c;typeof define==="function"&&define.amd&&define.amd.jQuery&&define("jquery",
[],function(){return c})})(window);
